CREATE PROCEDURE [dbo].[ISP_InsertOrderFeedback] --'<Json><OrderId>76628</OrderId><OrderProductId></OrderProductId><feedbackId>1227</feedbackId><ItemFeedbackName>1201</ItemFeedbackName><Attachment></Attachment><Comment>Test Feedback 3</Comment><ActualReceiveDate>19/10/2018</ActualReceiveDate><HVBLComment></HVBLComment><Quantity>0</Quantity><CreatedBy>12</CreatedBy><DocumentsList><DocumentName>DummyImage.png</DocumentName><DocumentExtension>png</DocumentExtension><DocumentBase64>iVBORw0KGgoAAAANSUhEUgAABIAAAAKICAIAAACHSRZaAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAABSzSURBVHhe7d0hVCJrHMZhI5FIJBKNRKKRaDQSiTYikWgkGo3GiRuJRCKRSLz3O3e+5XDXVXcV3lX3eRL8Z2BonN+ZmW8u/gEAACBCgAEAAIQIMAAAgBABBgAAECLAAAAAQgQYAABAiAADAAAIEWAAAAAhAgwAACBEgAEAAIQIMAAAgBABBgAAECLAAAAAQgQYAABAiAADAAAIEWAAAAAhAgwAACBEgAEAAIQIMAAAgBABBgAAECLAAAAAQgQYAABAiAADAAAIEWAAAAAhAgwAACBEgAEAAIQIMAAAgBABBgAAECLAAAAAQgQYAABAiAADAAAIEWAAAAAhAgwAACBEgAEAAIQIMAAAgBABBgAAECLAAAAAQgQYAABAiAADAAAIEWAAAAAhAgwAACBEgAEAAIQIMAAAgBABBgAAECLAAAAAQgQYAABAiAADAAAIEWAAAAAhAgwAACBEgAEAAIQIMAAAgBABBgAAECLAAAAAQgQYAABAiAADAAAIEWAAAAAhAgwAACBEgAEAAIQIMAAAgBABBgAAECLAAAAAQgQYAABAiAADAAAIEWAAAAAhAgwAACBEgAEAAIQIMAAAgBABBgAAECLAAAAAQgQYAABAiAADAAAIEWAAAAAhAgwAACBEgAEAAIQIMAAAgBABBgAAECLAAAAAQgQYAABAiAADAAAIEWAAAAAhAgwAACBEgAEAAIQIMAAAgBABBgAAECLAAAAAQgQYAABAiAADAAAIEWAAAAAhAgwAACBEgAEAAIQIMAAAgBABBgAAECLAAAAAQgQYAABAiAADAAAIEWAAAAAhAgwAACBEgAEAAIQIMAAAgBABBgAAECLAAAAAQgQYAABAiAADAAAIEWAAAAAhAgwAACBEgAEAAIQIMAAAgBABBgAAECLAAAAAQgQYAABAiAADAAAIEWAAAAAhAgwAACBEgAEAAIQIMAAAgBABBgAAECLAAAAAQgQYAABAiAADAAAIEWAAAAAhAgwAACBEgAEAAIQIMAAAgBABBgAAECLAAAAAQgQYAABAiAADAAAIEWAAAAAhAgwAACBEgAEAAIQIMAAAgBABBgAAECLAAAAAQgQYAABAiAADAAAIEWAAAAAhAgzgb7Hf75ummc/n19fX/X7/4rvyerlc1p0AgHMSYABfX4muwWBQe+tnOp1O3RUAOCcBBvCVNU3zcnod1A8AAOfkHxfga9put9fX17WuvhsOh5PJ5O7u7tu3b+1unU6n3bRardoJAHA+AgzgCyqJ1e1227Iqyuv5fF63/d8h0sbjcR0BAGcjwAC+lN1u98OJr/J2u93WzU+sVqu638XFZrOpUwDgPAQYwNdRaur4jq/yummauu15V1dX7f7PnSUDAE5FgAF8ESWfDjd0FZPJZL/f120vWi6X7UeGw2EdAQDnIcAAPr0fljosGXZ/f1+3/YLdbncoN1chAsBZCTCAT+zpUoelxNbrdd38y1yFCAAZAgzgs1osFsdLHXY6nZJPv3jZ4Q9chQgAGQIM4FOazWZtMrXG4/ELSx2+ylWIAJAhwAA+n+P6GgwGj4+PdcM7uAoRAAIEGMAnc1xfpZreds3hU65CBIAAAQbwmSwWizaTihPWV3F8FeJ7rmYEAF4gwAA+jaZpDo102vpqjUaj9ssfHh7qCAA4KQEG8Dlst9ter9cGUimlk9dXMZ1O2+8vL+oIADgpAQbwORxOT5UMO9Mlgg8PD+0hyrHqCAA4KQEG8Anc3t62adTpdJqmqdNTK113OMo5zrABAAIM4KM7nJgqFotFnZ5Hv99vD7RareoIADgdAQbwoW02m26320bReDyu07O5vr5uj3Xu0gOAv5MAA/i49vv9cDhsi2gwGAQuCzwsc19KrI4AgNMRYAAf183NTZtDnU5nvV7X6TmtVqv2iP1+v44AgNMRYAAf1HK5bFuouL+/r9Mz2+/3h0eNbTabOgUATkSAAXxE6/X6EELhp3Id1ruPVR8A/D0EGMCHs9vtBoNBW0HD4TC8IvxsNmsP7XHMAHByAgzgwxmPx20Cdbvd/HWATdO0R7+8vKwjAOBEBBjAx3JYh7B4eHio06DdblcPf3FRXtcpAHAKAgzgA9lut4dbvyaTSZ3GXV5etr/hjxQgAHxhAgzgA5lOp235ZJ769ZzDz5jNZnUEAJyCAAP4QHq9Xls+f/bUUzl6+zNGo1EdAQCnIMAAPpA2e4r6/g853AbW6XT+4Ik4APh6BBjAB9JmT1Hf/zmH28CapqkjAODdBBjAB9I2T7FcLv/sCoSTyaT9JYvFoo4AgHcTYAAfyGEJxNZwOCz9s16v6+agUoDtbxiPx3UEALybAAP4QG5vb9vs+UG/359Op4+Pj3W/89tsNu2hu91uHQEA7ybAAD6W9Xq9WCyGw2HbPz8oOXRzc5M5J1aqrz3oarWqIwDgfQQYwAe12+2Wy+X19XWJrjaEjo1Go/v7+7rreZTSa4/lNjAAOBUBBvAJPD4+TqfTwympgzKZz+dnWq7jcBtYKbE6AgDeR4ABfCar1epwYuqg0+mU4cnvEDvcBlYyr44AgPcRYACfz3a7vb29fXppYq/Xm06nJ7xD7HCIEmN1BAC8gwAD+Kz2+/1yuRwMBm0jHSvDu7u70ml117caj8ftF5YD1REA8A4CDODTa5rm5ubmp2t1lIK6v78vqVZ3/U2LxaL9nul0WkcAwDsIMICvo7TW9fV1m0zHSpuV+XK5/N0rCVerVfsNl5eXdQQAvIMAA/hqdrvd3d3dc08SGwwG0+n04eHhF0+LHU6snWmtRQD4qwgwgC9rs9nMZrOni9cflEibz+ffvn2rH/iZQ8h5HDMAvJ8AA/j6SjstFourq6s2pZ7qdrs3NzdN09QPHDmsw3HyZe4B4C8kwAD+Ivv9vn2m80/XTiz6/f5sNju+Vazs3G66u7urIwDgrQQYwF+qVNZyuby+vv7p8olXV1dlawm2w0KIt7e39ZMAwFsJMACeXci+TA73gJVUq3sDAG8lwACo2ic7P3er2Gg0qvsBAG8lwAD40Wazmc/nPyyf2Ov13vxAZwCgJcAAeNZyuTy+LnEwGLy8Zj0A8DIBBsBLttttr9erBfaf+XxetwEAv0mAAfCK0WhU2+u72WxWtwEAv0OAAfCKm5ubtruOL0fUYADwBgIMgFeU1jpE1/EaiRoMAH6XAAPgFcvlsi2uyWSy3+81GAC8mQAD4BVN07S5VdKrvNVgAPBmAgyAV6zX67a1Li8v24kGA4C3EWAAvKLkVhta3W63jp402N3dXd0AADxPgAHwusOjwOr7/xw3WKfTaZqmbgAAniHAAHjdYrEolTUej+v770qDDYfDtsG63e5ms6kbAICfEWAAvMt2u+33+22DlRe73a5uAACeEGAAvNdqtep0Om2DjUaj/X5fNwAA/yfAADiBh4eHNsCKyWRSpwDA/wkwAE5jPp/XAru4cDMYAPyUAAPgZA4LciyXyzoCAI4IMABOZjabtQF2c3NTRwDAEQEGwMk0TdMGWL/fryMA4IgAA+Bk9vv9YTnE1WpVpwDAdwIMgGc9Pj72//Pr93SNx+M2wJ4+tRkAEGAAPKukV1tTRXk9nU63223d9ozValU/cOEvBgB+5N8RgGcdryzf6nQ6ZVg3P6PuKsAA4An/jgC85KcN1jRN3fwzdT8BBgBP+HcE4Jc8PDwcFtgoer3eaDS6vb0thVZ6bL1et7u5BBEAXuDfEYBfVXKrptUzjgutqB8DAL7z7wjAb1itVtPp9HhxjudcXV3VzwAA3wkwAN5ivV43TTOfz29vb0ej0WAwaLur1+tNJpOXbxIDgL+WAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAAgRYAAAACECDAAAIESAAQAAhAgwAACAEAEGAAAQIsAAAABCBBgAAECIAAMAAIj4559/AR8TOkCaxCV7AAAAAElFTkSuQmCC</DocumentBase64><ObjectType>Feedback</ObjectType><SequenceNo>0</SequenceNo><CreatedBy>12</CreatedBy><IsActive>1</IsActive></DocumentsList></Json>'
@xmlDoc xml 
AS 
 BEGIN 
 SET ARITHABORT ON 
 DECLARE @TranName NVARCHAR(255) 
 DECLARE @ErrMsg NVARCHAR(2048) 
 DECLARE @ErrSeverity INT; 
 DECLARE @intPointer INT; 
 SET @ErrSeverity = 15; 

  BEGIN TRY
   EXEC sp_xml_preparedocument @intpointer OUTPUT,@xmlDoc

        Declare @orderProductId bigint
  Declare @returnQuantity decimal(10,2)

  INSERT INTO [dbo].[OrderFeedback]
           (
       [OrderId]
      ,[OrderProductId]
      ,[feedbackId]
	  ,[Field1]
      ,[Attachment]
      ,[Comment]
      ,[HVBLComment]
      ,[Quantity]
	  ,[ParentOrderFeedbackReplyId]
      ,[ActualReceiveDate]
      ,[CreatedBy]
      ,[CreatedDate]
      ,[IsActive]
      ,[IsRead]
     )

        SELECT
         tmp.[OrderId],
         tmp.[OrderProductId],
         tmp.[feedbackId],
		 tmp.[ItemFeedbackName],
         tmp.[Attachment],
         tmp.[Comment],
         tmp.[HVBLComment],
         tmp.[Quantity],
		 tmp.[ParentOrderFeedbackReplyId],
         convert(datetime,tmp.[ActualReceiveDate], 103),
         tmp.[CreatedBy],
         GETDATE(),
   1,
   0
            FROM OPENXML(@intpointer,'Json',2)
        WITH
        (
            [OrderId] bigint,
   [OrderProductId] bigint,
   [feedbackId] bigint,
   [ItemFeedbackName] bigint,
            [Attachment] nvarchar(500),
            [Comment] nvarchar(500),
            [HVBLComment]  nvarchar(500),
            [Quantity] decimal(18,2),
			[ParentOrderFeedbackReplyId] bigint,
            [ActualReceiveDate] nvarchar(50),
   [CreatedBy] bigint
        )tmp


   DECLARE @OrderFeedback bigint
     SET @OrderFeedback = @@IDENTITY


   INSERT INTO [Documents]
        (
         [DocumentName],
         [DocumentExtension],
   [DocumentBase64],
         [ObjectId],
         [ObjectType],
   [SequenceNo],
         [CreatedBy],
         [CreatedDate],         
         [IsActive]
         
        )
  SELECT
         tmp.[DocumentName],
         tmp.[DocumentExtension],
         tmp.[DocumentBase64],
         @OrderFeedback,
		 tmp.[ObjectType],
         tmp.[SequenceNo],
         tmp.[CreatedBy],
         GETDATE(),
			1
            FROM OPENXML(@intpointer,'Json/DocumentsList',2)
        WITH
        (
            [DocumentName] nvarchar(50),
			[DocumentExtension] nvarchar(50),
			[DocumentBase64] nvarchar(max),
            [ObjectId] bigint,
            [ObjectType] nvarchar(500),
            [SequenceNo]  bigint,
            [CreatedBy] bigint,
            [IsActive] bit
        )tmp


  SELECT 
    @orderProductId = tmp1.[OrderProductId],
    @returnQuantity=tmp1.ReturnQuantity
   
   

FROM OPENXML(@intpointer,'Json',2)
   WITH
   (
   [OrderProductId] bigint,
   ReturnQuantity decimal(10,2)
           
   )tmp1
  


  update [OrderProduct] set ReturnQuantity=@returnQuantity where OrderProductId=@orderProductId

        --Add child table insert procedure when required.

		Declare @createdBy bigint
		Declare @orderId bigint
		Declare @roleName nvarchar(50)
  
   Select * into #tmpCreatedBy  FROM OPENXML(@intpointer,'Json',2)
        WITH
        (
            [CreatedBy] bigint,
			[OrderId] bigint
          
           
        )tmp

		SET @createdBy=(Select  #tmpCreatedBy.[CreatedBy] from #tmpCreatedBy)
		SET @orderId=(Select  #tmpCreatedBy.[OrderId] from #tmpCreatedBy)
		SET @roleName=(Select RoleName from RoleMaster where RoleMasterId = (Select RoleMasterId from Login where LoginId=@createdBy))
		if @roleName='Customer'
		BEGIN
		INSERT INTO [dbo].[EventNotification]
           ([EventMasterId]
           ,[EventCode]
           ,[ObjectId]
           ,[ObjectType]
           ,[IsActive]
           ,[CreatedBy]
           ,[CreatedDate])
		Select (Select top 1 EventMasterId from EventMaster where EventCode='ComplaintReceivedFromCustomer' and IsActive=1),'ComplaintReceivedFromCustomer',@orderId,'Order',1,1,GETDATE() 
		END
		ELSE
		BEGIN
			INSERT INTO [dbo].[EventNotification]
           ([EventMasterId]
           ,[EventCode]
           ,[ObjectId]
           ,[ObjectType]
           ,[IsActive]
           ,[CreatedBy]
           ,[CreatedDate])
		Select (Select top 1 EventMasterId from EventMaster where EventCode='FeedbackReceivedFromCustomerService' and IsActive=1),'FeedbackReceivedFromCustomerService',@orderId,'Order',1,1,GETDATE() 
		END
    
  SELECT @OrderFeedback as OrderFeedback FOR XML RAW('Json'),ELEMENTS
    
    exec sp_xml_removedocument @intPointer  
    END TRY
    BEGIN CATCH
    SELECT @ErrMsg = ERROR_MESSAGE(); 
    RAISERROR(@ErrMsg, @ErrSeverity, 1); 
    RETURN; 
    END CATCH
END
