/*
 * WebAPIBuild
 *
 * This is glassRUN web api library for 3rd party and internal reference
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class ConfigurationsApiController : ControllerBase, IConfigurationsApiController
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/Configurations/AdvertisingBannerList")]
        [ValidateModelState]
        [SwaggerOperation("ConfigurationsAdvertisingBannerListPost")]
        public virtual IActionResult ConfigurationsAdvertisingBannerListPost([FromBody]GlassRUNServiceWebApiConfigurationsDTOAdvertisingBannerDTO body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/Configurations/BrandList")]
        [ValidateModelState]
        [SwaggerOperation("ConfigurationsBrandListPost")]
        public virtual IActionResult ConfigurationsBrandListPost([FromBody]GlassRUNServiceWebApiConfigurationsDTOBrandDTO body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/Configurations/CheckAppVersion")]
        [ValidateModelState]
        [SwaggerOperation("ConfigurationsCheckAppVersionPost")]
        public virtual IActionResult ConfigurationsCheckAppVersionPost([FromBody]GlassRUNServiceWebApiConfigurationsDTOAppLatestVersionDTO body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/Configurations/ConfigurationModifyAPI")]
        [ValidateModelState]
        [SwaggerOperation("ConfigurationsConfigurationModifyAPIPost")]
        public virtual IActionResult ConfigurationsConfigurationModifyAPIPost([FromBody]GlassRUNServiceWebApiConfigurationsDTOConfigurationModificationStatusDTO body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/Configurations/GelLanguageResource")]
        [ValidateModelState]
        [SwaggerOperation("ConfigurationsGelLanguageResourceGet")]
        public virtual IActionResult ConfigurationsGelLanguageResourceGet()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/Configurations/GetAllFilterParametersByPageId")]
        [ValidateModelState]
        [SwaggerOperation("ConfigurationsGetAllFilterParametersByPageIdPost")]
        public virtual IActionResult ConfigurationsGetAllFilterParametersByPageIdPost([FromBody] body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/Configurations/GetAllSortingParametersByPageId")]
        [ValidateModelState]
        [SwaggerOperation("ConfigurationsGetAllSortingParametersByPageIdPost")]
        public virtual IActionResult ConfigurationsGetAllSortingParametersByPageIdPost([FromBody] body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/Configurations/GetAppPageControlAccessByPageIdAndRoleAndUserID")]
        [ValidateModelState]
        [SwaggerOperation("ConfigurationsGetAppPageControlAccessByPageIdAndRoleAndUserIDPost")]
        public virtual IActionResult ConfigurationsGetAppPageControlAccessByPageIdAndRoleAndUserIDPost([FromBody] body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/Configurations/GetCultureConfigurations")]
        [ValidateModelState]
        [SwaggerOperation("ConfigurationsGetCultureConfigurationsGet")]
        public virtual IActionResult ConfigurationsGetCultureConfigurationsGet()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/Configurations/GetLookUpDetails")]
        [ValidateModelState]
        [SwaggerOperation("ConfigurationsGetLookUpDetailsGet")]
        public virtual IActionResult ConfigurationsGetLookUpDetailsGet()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="roleId"></param>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/Configurations/GetPageControlConfigurations")]
        [ValidateModelState]
        [SwaggerOperation("ConfigurationsGetPageControlConfigurationsGet")]
        public virtual IActionResult ConfigurationsGetPageControlConfigurationsGet([FromQuery]long? roleId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="companyId"></param>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/Configurations/GetPageValidations")]
        [ValidateModelState]
        [SwaggerOperation("ConfigurationsGetPageValidationsGet")]
        public virtual IActionResult ConfigurationsGetPageValidationsGet([FromQuery]long? companyId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="companyId"></param>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/Configurations/GetSetting")]
        [ValidateModelState]
        [SwaggerOperation("ConfigurationsGetSettingGet")]
        public virtual IActionResult ConfigurationsGetSettingGet([FromQuery]long? companyId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/Configurations/GetStatusWiseColorList")]
        [ValidateModelState]
        [SwaggerOperation("ConfigurationsGetStatusWiseColorListPost")]
        public virtual IActionResult ConfigurationsGetStatusWiseColorListPost([FromBody]GlassRUNServiceWebApiConfigurationsDTOColorStatusDTO body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/Configurations/LoadAllAppFormList")]
        [ValidateModelState]
        [SwaggerOperation("ConfigurationsLoadAllAppFormListPost")]
        public virtual IActionResult ConfigurationsLoadAllAppFormListPost([FromBody] body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/Configurations/PageLevelConfigurationForApp")]
        [ValidateModelState]
        [SwaggerOperation("ConfigurationsPageLevelConfigurationForAppPost")]
        public virtual IActionResult ConfigurationsPageLevelConfigurationForAppPost([FromBody] body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }
    }
}
