/*
 * WebAPIBuild
 *
 * This is glassRUN web api library for 3rd party and internal reference
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public interface IBayApiController
    { 
        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult BayCancelOrderAndReQueueSequenceNumberPost([FromBody] body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult BayCreateBayDetailsPost([FromBody] body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult BayDeactivatedAndActivatedBayPost([FromBody]GlassRUNServiceWebAPIManageBayDTOBayDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult BayEndOrderForForkLiftDriverPost([FromBody] body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult BayGetAllBayListForForkLiftPost([FromBody]GlassRUNServiceWebAPIManageBayDTOBaySearchDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult BayGetAllBayListPost([FromBody]GlassRUNServiceWebAPIManageBayDTOBaySearchDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult BayGetOrderDetailsForBayPost([FromBody] body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult BayGetUnassignedBayQueueDetailsPost([FromBody] body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult BayLoadBayDetailsOnPopupPost([FromBody] body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult BayLoadCapsuleDetailsPost([FromBody] body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult BayLoadForkListActivityViewDetailsPost([FromBody]GlassRUNServiceWebAPIManageBayDTOBaySearchDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult BayLoadHorizontalQueueOnPopupPost([FromBody] body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult BayLodQueueDetailsPost([FromBody] body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult BayProceedToQueuePost([FromBody]GlassRUNServiceWebAPIManageBayDTOBayDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult BayResetOrderForForkLiftDriverPost([FromBody] body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult BaySearchHistoricalDataTransactionListPost([FromBody]GlassRUNServiceWebAPIManageBayDTOBaySearchDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult BayStartOrderForForkLiftDriverPost([FromBody] body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult BayUpdateBayDetailsPost([FromBody]GlassRUNServiceWebAPIManageBayDTOBayDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult BayUpdateBayForForkListDriverPost([FromBody]GlassRUNServiceWebAPIManageBayDTOBaySearchDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult BayUpdatePriorityDetailsPost([FromBody]GlassRUNServiceWebAPIManageBayDTOBaySearchDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult BayUpdateRequestBayPost([FromBody]GlassRUNServiceWebAPIManageBayDTOBaySearchDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult BayUpdateTruckSequenceAfterLoadingEndPost([FromBody]GlassRUNServiceWebAPIManageBayDTOBayDTO body);
    }
}
