/*
 * WebAPIBuild
 *
 * This is glassRUN web api library for 3rd party and internal reference
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public interface IConfigurationsApiController
    { 
        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ConfigurationsAdvertisingBannerListPost([FromBody]GlassRUNServiceWebApiConfigurationsDTOAdvertisingBannerDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ConfigurationsBrandListPost([FromBody]GlassRUNServiceWebApiConfigurationsDTOBrandDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ConfigurationsCheckAppVersionPost([FromBody]GlassRUNServiceWebApiConfigurationsDTOAppLatestVersionDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ConfigurationsConfigurationModifyAPIPost([FromBody]GlassRUNServiceWebApiConfigurationsDTOConfigurationModificationStatusDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <response code="200">Success</response>
        IActionResult ConfigurationsGelLanguageResourceGet();

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ConfigurationsGetAllFilterParametersByPageIdPost([FromBody] body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ConfigurationsGetAllSortingParametersByPageIdPost([FromBody] body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ConfigurationsGetAppPageControlAccessByPageIdAndRoleAndUserIDPost([FromBody] body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <response code="200">Success</response>
        IActionResult ConfigurationsGetCultureConfigurationsGet();

        /// <summary>
        /// 
        /// </summary>
        
        /// <response code="200">Success</response>
        IActionResult ConfigurationsGetLookUpDetailsGet();

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="roleId"></param>
        /// <response code="200">Success</response>
        IActionResult ConfigurationsGetPageControlConfigurationsGet([FromQuery]long? roleId);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="companyId"></param>
        /// <response code="200">Success</response>
        IActionResult ConfigurationsGetPageValidationsGet([FromQuery]long? companyId);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="companyId"></param>
        /// <response code="200">Success</response>
        IActionResult ConfigurationsGetSettingGet([FromQuery]long? companyId);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ConfigurationsGetStatusWiseColorListPost([FromBody]GlassRUNServiceWebApiConfigurationsDTOColorStatusDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ConfigurationsLoadAllAppFormListPost([FromBody] body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ConfigurationsPageLevelConfigurationForAppPost([FromBody] body);
    }
}
