/*
 * WebAPIBuild
 *
 * This is glassRUN web api library for 3rd party and internal reference
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public interface IDeliveryAppApiController
    { 
        /// <summary>
        /// (Need developer help).
        /// </summary>
        /// <remarks>(Need developer help).</remarks>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        /// <response code="0">successful operation</response>
        IActionResult AllJsonFromDeliveryApp([FromBody] body);

        /// <summary>
        /// API used to get order document data from Delivery App as defined in glassRUN.
        /// </summary>
        /// <remarks>This API is used to order document data as per the activity on glassRUN Delivery App.</remarks>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        /// <response code="0">successful operation</response>
        IActionResult GetDocumentData([FromBody] body);

        /// <summary>
        /// API used to update the last sync of records from Delivery App as defined in glassRUN.
        /// </summary>
        /// <remarks>This API is used to update when the records were last synced as per the activity on glassRUN Delivery App.</remarks>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        /// <response code="0">successful operation</response>
        IActionResult LastSyncRecordFromDeliveryApp([FromBody] body);

        /// <summary>
        /// (Need developer help).
        /// </summary>
        /// <remarks>(Need developer help).</remarks>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        /// <response code="0">successful operation</response>
        IActionResult OrderMovementFromDeliveryApp([FromBody] body);

        /// <summary>
        /// API used to update the order products from Delivery App as defined in glassRUN.
        /// </summary>
        /// <remarks>This API is used to update order product data as per the activity on glassRUN Delivery App.</remarks>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        /// <response code="0">successful operation</response>
        IActionResult OrderProductFromDeliveryApp([FromBody] body);

        /// <summary>
        /// (Need developer help).
        /// </summary>
        /// <remarks>(Need developer help).</remarks>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        /// <response code="0">successful operation</response>
        IActionResult OrderProductMovementFromDeliveryApp([FromBody] body);

        /// <summary>
        /// API used to update the order from Delivery App as defined in glassRUN.
        /// </summary>
        /// <remarks>This API is used to update order data as per the activity on glassRUN Delivery App.</remarks>
        /// <param name="body"></param>
        IActionResult UpDateOrderFromDeliveryApp([FromBody] body);

        /// <summary>
        /// (Need developer help).
        /// </summary>
        /// <remarks>(Need developer help).</remarks>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        /// <response code="0">successful operation</response>
        IActionResult UpdateOrderDocumentFromDeliveryApp([FromBody] body);
    }
}
