/*
 * WebAPIBuild
 *
 * This is glassRUN web api library for 3rd party and internal reference
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public interface IManageLoginApiController
    { 
        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ApiManageLoginActivateDeactivateCompanyPost([FromBody]GlassRUNServiceWebApiManageLoginDTOLoginDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ApiManageLoginChangePasswordPost([FromBody]GlassRUNServiceWebApiManageLoginDTOLoginDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ApiManageLoginContactInformationUpDatePost([FromBody]GlassRUNServiceWebApiManageLoginDTOLoginDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ApiManageLoginDeleteLoginByLoginIdPost([FromBody] body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ApiManageLoginGetAllDataPost([FromBody] body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ApiManageLoginGetAppNotificationsByUserIdPost([FromBody]GlassRUNServiceWebApiManageLoginDTOLoginDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ApiManageLoginGetChildUserListPost([FromBody]GlassRUNServiceWebApiManageLoginDTOLoginDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ApiManageLoginGetLocationDetailsPost([FromBody] body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ApiManageLoginGetProfileDetailsPost([FromBody] body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ApiManageLoginGetSuperUserListPost([FromBody]GlassRUNServiceWebApiManageLoginDTOUserOutletMappingDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ApiManageLoginInsertLoginOTPPost([FromBody]GlassRUNServiceWebApiManageLoginDTOLoginDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ApiManageLoginLoadProfileLocationDetailsPost([FromBody] body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ApiManageLoginRegenerateOTPPost([FromBody] body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ApiManageLoginSaveUserOutletMappingPost([FromBody]GlassRUNServiceWebApiManageLoginDTOUserOutletMappingDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ApiManageLoginUpdateLanguageForUserPost([FromBody]GlassRUNServiceWebApiManageLoginDTOLoginDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="json"></param>
        /// <response code="200">Success</response>
        IActionResult ApiManageLoginUpdateProfileDetailsPost([FromQuery] json);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ApiManageLoginUpdateRegeneratedLoginOTPPost([FromBody]GlassRUNServiceWebApiManageLoginDTOLoginDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="json"></param>
        /// <response code="200">Success</response>
        IActionResult ApiManageLoginUploadLocationDetailsPost([FromQuery] json);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ApiManageLoginValidateB2BLoginPost([FromBody] body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ApiManageLoginValidateLoginPost([FromBody]GlassRUNServiceWebApiManageLoginDTOLoginDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ApiManageLoginValidateUserNameAndMobileNumberPost([FromBody]GlassRUNServiceWebApiManageLoginDTOLoginDTO body);

        /// <summary>
        /// 
        /// </summary>
        
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult ApiManageLoginValidateUserNamePost([FromBody] body);
    }
}
