/*
 * WebAPIBuild
 *
 * This is glassRUN web api library for 3rd party and internal reference
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public interface IOrderMovementApiController
    { 
        /// <summary>
        /// API to update delivery confirmation done by driver.
        /// </summary>
        /// <remarks>This API is used by gRUN to update delivery confirmation done by driver from Driver App.</remarks>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult UpdateDeliveryConfirmationByDriver([FromBody]GlassRUNServiceWebApiManageOrderDTOOrderMovementDTO body);

        /// <summary>
        /// API to update Order Movement.
        /// </summary>
        /// <remarks>This API is used by gRUN to update Order movement. (Developer to reconfirm).</remarks>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult UpdateOrderMovement([FromBody]GlassRUNServiceWebApiManageOrderDTOOrderMovementDTO body);
    }
}
