/*
 * WebAPIBuild
 *
 * This is glassRUN web api library for 3rd party and internal reference
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public interface ISchedulingApiController
    { 
        /// <summary>
        /// API for Order scheduling by Transporter.
        /// </summary>
        /// <remarks>This API is used by gRUN for Order scheduling done by Transporter. (Developer to reconfirm).</remarks>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult OrderScheduling([FromBody]GlassRUNServiceWebApiManageOrderDTOOrderSchedulingDTO body);

        /// <summary>
        /// API for Order scheduling flow.
        /// </summary>
        /// <remarks>This API is used by gRUN for Order scheduling flow. (Developer to reconfirm).</remarks>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult OrderSchedulingFlow([FromBody] body);

        /// <summary>
        /// API for auto update of Order sequencing during scheduling.
        /// </summary>
        /// <remarks>This API is used by gRUN for auto order sequencing during scheduling. (Developer to reconfirm).</remarks>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult UpdateSequenceAuto([FromBody] body);

        /// <summary>
        /// API for Manual updating of Order sequencing by transporter.
        /// </summary>
        /// <remarks>This API is used by gRUN for manual order sequencing done by transporter. (Developer to reconfirm).</remarks>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        IActionResult UpdateSequenceManual([FromBody]GlassRUNServiceWebApiManageOrderDTOOrderSchedulingDTO body);
    }
}
