/*
 * WebAPIBuild
 *
 * This is glassRUN web api library for 3rd party and internal reference
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class ManageLoginApiController : ControllerBase, IManageLoginApiController
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/ManageLogin/ActivateDeactivateCompany")]
        [ValidateModelState]
        [SwaggerOperation("ApiManageLoginActivateDeactivateCompanyPost")]
        public virtual IActionResult ApiManageLoginActivateDeactivateCompanyPost([FromBody]GlassRUNServiceWebApiManageLoginDTOLoginDTO body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/ManageLogin/ChangePassword")]
        [ValidateModelState]
        [SwaggerOperation("ApiManageLoginChangePasswordPost")]
        public virtual IActionResult ApiManageLoginChangePasswordPost([FromBody]GlassRUNServiceWebApiManageLoginDTOLoginDTO body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/ManageLogin/ContactInformationUpDate")]
        [ValidateModelState]
        [SwaggerOperation("ApiManageLoginContactInformationUpDatePost")]
        public virtual IActionResult ApiManageLoginContactInformationUpDatePost([FromBody]GlassRUNServiceWebApiManageLoginDTOLoginDTO body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/ManageLogin/DeleteLoginByLoginId")]
        [ValidateModelState]
        [SwaggerOperation("ApiManageLoginDeleteLoginByLoginIdPost")]
        public virtual IActionResult ApiManageLoginDeleteLoginByLoginIdPost([FromBody] body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/ManageLogin/GetAllData")]
        [ValidateModelState]
        [SwaggerOperation("ApiManageLoginGetAllDataPost")]
        public virtual IActionResult ApiManageLoginGetAllDataPost([FromBody] body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/ManageLogin/GetAppNotificationsByUserId")]
        [ValidateModelState]
        [SwaggerOperation("ApiManageLoginGetAppNotificationsByUserIdPost")]
        public virtual IActionResult ApiManageLoginGetAppNotificationsByUserIdPost([FromBody]GlassRUNServiceWebApiManageLoginDTOLoginDTO body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/ManageLogin/GetChildUserList")]
        [ValidateModelState]
        [SwaggerOperation("ApiManageLoginGetChildUserListPost")]
        public virtual IActionResult ApiManageLoginGetChildUserListPost([FromBody]GlassRUNServiceWebApiManageLoginDTOLoginDTO body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/ManageLogin/GetLocationDetails")]
        [ValidateModelState]
        [SwaggerOperation("ApiManageLoginGetLocationDetailsPost")]
        public virtual IActionResult ApiManageLoginGetLocationDetailsPost([FromBody] body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/ManageLogin/GetProfileDetails")]
        [ValidateModelState]
        [SwaggerOperation("ApiManageLoginGetProfileDetailsPost")]
        public virtual IActionResult ApiManageLoginGetProfileDetailsPost([FromBody] body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/ManageLogin/GetSuperUserList")]
        [ValidateModelState]
        [SwaggerOperation("ApiManageLoginGetSuperUserListPost")]
        public virtual IActionResult ApiManageLoginGetSuperUserListPost([FromBody]GlassRUNServiceWebApiManageLoginDTOUserOutletMappingDTO body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/ManageLogin/InsertLoginOTP")]
        [ValidateModelState]
        [SwaggerOperation("ApiManageLoginInsertLoginOTPPost")]
        public virtual IActionResult ApiManageLoginInsertLoginOTPPost([FromBody]GlassRUNServiceWebApiManageLoginDTOLoginDTO body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/ManageLogin/LoadProfileLocationDetails")]
        [ValidateModelState]
        [SwaggerOperation("ApiManageLoginLoadProfileLocationDetailsPost")]
        public virtual IActionResult ApiManageLoginLoadProfileLocationDetailsPost([FromBody] body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/ManageLogin/RegenerateOTP")]
        [ValidateModelState]
        [SwaggerOperation("ApiManageLoginRegenerateOTPPost")]
        public virtual IActionResult ApiManageLoginRegenerateOTPPost([FromBody] body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/ManageLogin/SaveUserOutletMapping")]
        [ValidateModelState]
        [SwaggerOperation("ApiManageLoginSaveUserOutletMappingPost")]
        public virtual IActionResult ApiManageLoginSaveUserOutletMappingPost([FromBody]GlassRUNServiceWebApiManageLoginDTOUserOutletMappingDTO body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/ManageLogin/UpdateLanguageForUser")]
        [ValidateModelState]
        [SwaggerOperation("ApiManageLoginUpdateLanguageForUserPost")]
        public virtual IActionResult ApiManageLoginUpdateLanguageForUserPost([FromBody]GlassRUNServiceWebApiManageLoginDTOLoginDTO body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="json"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/ManageLogin/UpdateProfileDetails")]
        [ValidateModelState]
        [SwaggerOperation("ApiManageLoginUpdateProfileDetailsPost")]
        public virtual IActionResult ApiManageLoginUpdateProfileDetailsPost([FromQuery] json)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/ManageLogin/UpdateRegeneratedLoginOTP")]
        [ValidateModelState]
        [SwaggerOperation("ApiManageLoginUpdateRegeneratedLoginOTPPost")]
        public virtual IActionResult ApiManageLoginUpdateRegeneratedLoginOTPPost([FromBody]GlassRUNServiceWebApiManageLoginDTOLoginDTO body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="json"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/ManageLogin/UploadLocationDetails")]
        [ValidateModelState]
        [SwaggerOperation("ApiManageLoginUploadLocationDetailsPost")]
        public virtual IActionResult ApiManageLoginUploadLocationDetailsPost([FromQuery] json)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/ManageLogin/ValidateB2BLogin")]
        [ValidateModelState]
        [SwaggerOperation("ApiManageLoginValidateB2BLoginPost")]
        public virtual IActionResult ApiManageLoginValidateB2BLoginPost([FromBody] body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/ManageLogin/ValidateLogin")]
        [ValidateModelState]
        [SwaggerOperation("ApiManageLoginValidateLoginPost")]
        public virtual IActionResult ApiManageLoginValidateLoginPost([FromBody]GlassRUNServiceWebApiManageLoginDTOLoginDTO body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/ManageLogin/ValidateUserNameAndMobileNumber")]
        [ValidateModelState]
        [SwaggerOperation("ApiManageLoginValidateUserNameAndMobileNumberPost")]
        public virtual IActionResult ApiManageLoginValidateUserNameAndMobileNumberPost([FromBody]GlassRUNServiceWebApiManageLoginDTOLoginDTO body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/api/ManageLogin/ValidateUserName")]
        [ValidateModelState]
        [SwaggerOperation("ApiManageLoginValidateUserNamePost")]
        public virtual IActionResult ApiManageLoginValidateUserNamePost([FromBody] body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }
    }
}
