/*
 * WebAPIBuild
 *
 * This is glassRUN web api library for 3rd party and internal reference
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class ManageCustomerApiController : ControllerBase, IManageCustomerApiController
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/ManageCustomer/GetAllCustomerListB2BApp")]
        [ValidateModelState]
        [SwaggerOperation("ManageCustomerGetAllCustomerListB2BAppPost")]
        public virtual IActionResult ManageCustomerGetAllCustomerListB2BAppPost([FromBody] body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/ManageCustomer/GetAllSupplierDetailsB2BApp")]
        [ValidateModelState]
        [SwaggerOperation("ManageCustomerGetAllSupplierDetailsB2BAppPost")]
        public virtual IActionResult ManageCustomerGetAllSupplierDetailsB2BAppPost([FromBody] body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/ManageCustomer/GetCustomerDetailsBySupplier")]
        [ValidateModelState]
        [SwaggerOperation("ManageCustomerGetCustomerDetailsBySupplierPost")]
        public virtual IActionResult ManageCustomerGetCustomerDetailsBySupplierPost([FromBody] body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/ManageCustomer/SaveCustomerGroup")]
        [ValidateModelState]
        [SwaggerOperation("ManageCustomerSaveCustomerGroupPost")]
        public virtual IActionResult ManageCustomerSaveCustomerGroupPost([FromBody] body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/ManageCustomer/UpadateManageCusomerDetailsB2BApp")]
        [ValidateModelState]
        [SwaggerOperation("ManageCustomerUpadateManageCusomerDetailsB2BAppPost")]
        public virtual IActionResult ManageCustomerUpadateManageCusomerDetailsB2BAppPost([FromBody] body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }
    }
}
