/*
 * WebAPIBuild
 *
 * This is glassRUN web api library for 3rd party and internal reference
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class OrderMovementApiController : ControllerBase, IOrderMovementApiController
    { 
        /// <summary>
        /// API to update delivery confirmation done by driver.
        /// </summary>
        /// <remarks>This API is used by gRUN to update delivery confirmation done by driver from Driver App.</remarks>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/OrderMovement/UpdateDeliveryConfirmationByDriver")]
        [ValidateModelState]
        [SwaggerOperation("UpdateDeliveryConfirmationByDriver")]
        public virtual IActionResult UpdateDeliveryConfirmationByDriver([FromBody]GlassRUNServiceWebApiManageOrderDTOOrderMovementDTO body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// API to update Order Movement.
        /// </summary>
        /// <remarks>This API is used by gRUN to update Order movement. (Developer to reconfirm).</remarks>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/OrderMovement/UpdateOrderMovement")]
        [ValidateModelState]
        [SwaggerOperation("UpdateOrderMovement")]
        public virtual IActionResult UpdateOrderMovement([FromBody]GlassRUNServiceWebApiManageOrderDTOOrderMovementDTO body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }
    }
}
