create FUNCTION [dbo].[DateJulianDateConv](@DATE INT)RETURNS INT WITH SCHEMABINDING 
AS  
BEGIN 
 RETURN CAST(CASE WHEN SUBSTRING(CAST(@DATE AS VARCHAR),1,4) <=1999 THEN 0 ELSE 1 END AS VARCHAR) + 
  SUBSTRING(CAST(@DATE AS VARCHAR),3,2) + 
  REPLACE(STR(CAST(LTRIM(@DATE) - DATEADD(YYYY,DATEDIFF(YYYY,0,LTRIM(@DATE)),0) AS INT)+1,3), ' ','0')

END
