/*
 * WebAPIBuild
 *
 * This is glassRUN web api library for 3rd party and internal reference
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class GlassRUNServiceWebApiManageOrderDTOOrderDTO : IEquatable<GlassRUNServiceWebApiManageOrderDTOOrderDTO>
    { 
        /// <summary>
        /// Gets or Sets BillTo
        /// </summary>
        [DataMember(Name="billTo")]
        public long? BillTo { get; set; }

        /// <summary>
        /// Gets or Sets BillToCode
        /// </summary>
        [DataMember(Name="billToCode")]
        public string BillToCode { get; set; }

        /// <summary>
        /// Gets or Sets DriverName
        /// </summary>
        [DataMember(Name="driverName")]
        public string DriverName { get; set; }

        /// <summary>
        /// Gets or Sets PlateNumber
        /// </summary>
        [DataMember(Name="plateNumber")]
        public string PlateNumber { get; set; }

        /// <summary>
        /// Gets or Sets BillToName
        /// </summary>
        [DataMember(Name="billToName")]
        public string BillToName { get; set; }

        /// <summary>
        /// Gets or Sets WorkFlowCode
        /// </summary>
        [DataMember(Name="workFlowCode")]
        public string WorkFlowCode { get; set; }

        /// <summary>
        /// Gets or Sets CarrierCode
        /// </summary>
        [DataMember(Name="carrierCode")]
        public string CarrierCode { get; set; }

        /// <summary>
        /// Gets or Sets CarrierETA
        /// </summary>
        [DataMember(Name="carrierETA")]
        public DateTime? CarrierETA { get; set; }

        /// <summary>
        /// Gets or Sets CarrierETD
        /// </summary>
        [DataMember(Name="carrierETD")]
        public DateTime? CarrierETD { get; set; }

        /// <summary>
        /// Gets or Sets CarrierName
        /// </summary>
        [DataMember(Name="carrierName")]
        public string CarrierName { get; set; }

        /// <summary>
        /// Gets or Sets CarrierNumber
        /// </summary>
        [DataMember(Name="carrierNumber")]
        public string CarrierNumber { get; set; }

        /// <summary>
        /// Gets or Sets Priority
        /// </summary>
        [DataMember(Name="priority")]
        public long? Priority { get; set; }

        /// <summary>
        /// Gets or Sets PriorityValue
        /// </summary>
        [DataMember(Name="priorityValue")]
        public string PriorityValue { get; set; }

        /// <summary>
        /// Gets or Sets LoginId
        /// </summary>
        [DataMember(Name="loginId")]
        public long? LoginId { get; set; }

        /// <summary>
        /// Gets or Sets CollectionLocationCode
        /// </summary>
        [DataMember(Name="collectionLocationCode")]
        public string CollectionLocationCode { get; set; }

        /// <summary>
        /// Gets or Sets CollectionLocationId
        /// </summary>
        [DataMember(Name="collectionLocationId")]
        public long? CollectionLocationId { get; set; }

        /// <summary>
        /// Gets or Sets CollectionLocationName
        /// </summary>
        [DataMember(Name="collectionLocationName")]
        public string CollectionLocationName { get; set; }

        /// <summary>
        /// Gets or Sets CompanyCode
        /// </summary>
        [DataMember(Name="companyCode")]
        public string CompanyCode { get; set; }

        /// <summary>
        /// Gets or Sets CompanyName
        /// </summary>
        [DataMember(Name="companyName")]
        public string CompanyName { get; set; }

        /// <summary>
        /// Gets or Sets CompanyId
        /// </summary>
        [DataMember(Name="companyId")]
        public long? CompanyId { get; set; }

        /// <summary>
        /// Gets or Sets CreatedBy
        /// </summary>
        [DataMember(Name="createdBy")]
        public long? CreatedBy { get; set; }

        /// <summary>
        /// Gets or Sets CreatedDate
        /// </summary>
        [DataMember(Name="createdDate")]
        public DateTime? CreatedDate { get; set; }

        /// <summary>
        /// Gets or Sets CurrentState
        /// </summary>
        [DataMember(Name="currentState")]
        public long? CurrentState { get; set; }

        /// <summary>
        /// Gets or Sets Description1
        /// </summary>
        [DataMember(Name="description1")]
        public string Description1 { get; set; }

        /// <summary>
        /// Gets or Sets Description2
        /// </summary>
        [DataMember(Name="description2")]
        public string Description2 { get; set; }

        /// <summary>
        /// Gets or Sets DiscountAmount
        /// </summary>
        [DataMember(Name="discountAmount")]
        public double? DiscountAmount { get; set; }

        /// <summary>
        /// Gets or Sets DiscountPercent
        /// </summary>
        [DataMember(Name="discountPercent")]
        public double? DiscountPercent { get; set; }

        /// <summary>
        /// Gets or Sets EnquiryId
        /// </summary>
        [DataMember(Name="enquiryId")]
        public long? EnquiryId { get; set; }

        /// <summary>
        /// Gets or Sets ExpectedTimeOfDelivery
        /// </summary>
        [DataMember(Name="expectedTimeOfDelivery")]
        public DateTime? ExpectedTimeOfDelivery { get; set; }

        /// <summary>
        /// Gets or Sets Field1
        /// </summary>
        [DataMember(Name="field1")]
        public string Field1 { get; set; }

        /// <summary>
        /// Gets or Sets Field10
        /// </summary>
        [DataMember(Name="field10")]
        public string Field10 { get; set; }

        /// <summary>
        /// Gets or Sets Field2
        /// </summary>
        [DataMember(Name="field2")]
        public string Field2 { get; set; }

        /// <summary>
        /// Gets or Sets Field3
        /// </summary>
        [DataMember(Name="field3")]
        public string Field3 { get; set; }

        /// <summary>
        /// Gets or Sets Field4
        /// </summary>
        [DataMember(Name="field4")]
        public string Field4 { get; set; }

        /// <summary>
        /// Gets or Sets Field5
        /// </summary>
        [DataMember(Name="field5")]
        public string Field5 { get; set; }

        /// <summary>
        /// Gets or Sets Field6
        /// </summary>
        [DataMember(Name="field6")]
        public string Field6 { get; set; }

        /// <summary>
        /// Gets or Sets Field7
        /// </summary>
        [DataMember(Name="field7")]
        public string Field7 { get; set; }

        /// <summary>
        /// Gets or Sets Field8
        /// </summary>
        [DataMember(Name="field8")]
        public string Field8 { get; set; }

        /// <summary>
        /// Gets or Sets Field9
        /// </summary>
        [DataMember(Name="field9")]
        public string Field9 { get; set; }

        /// <summary>
        /// Gets or Sets GratisCode
        /// </summary>
        [DataMember(Name="gratisCode")]
        public string GratisCode { get; set; }

        /// <summary>
        /// Gets or Sets HoldStatus
        /// </summary>
        [DataMember(Name="holdStatus")]
        public string HoldStatus { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceNumber
        /// </summary>
        [DataMember(Name="invoiceNumber")]
        public string InvoiceNumber { get; set; }

        /// <summary>
        /// Gets or Sets EInvoiceNumber
        /// </summary>
        [DataMember(Name="eInvoiceNumber")]
        public string EInvoiceNumber { get; set; }

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        [DataMember(Name="isActive")]
        public bool? IsActive { get; set; }

        /// <summary>
        /// Gets or Sets IsAdhoc
        /// </summary>
        [DataMember(Name="isAdhoc")]
        public bool? IsAdhoc { get; set; }

        /// <summary>
        /// Gets or Sets IsInventoryTransfer
        /// </summary>
        [DataMember(Name="isInventoryTransfer")]
        public bool? IsInventoryTransfer { get; set; }

        /// <summary>
        /// Gets or Sets IsLockFromWMS
        /// </summary>
        [DataMember(Name="isLockFromWMS")]
        public long? IsLockFromWMS { get; set; }

        /// <summary>
        /// Gets or Sets IsPickConfirmed
        /// </summary>
        [DataMember(Name="isPickConfirmed")]
        public bool? IsPickConfirmed { get; set; }

        /// <summary>
        /// Gets or Sets IsPrintPickSlip
        /// </summary>
        [DataMember(Name="isPrintPickSlip")]
        public bool? IsPrintPickSlip { get; set; }

        /// <summary>
        /// Gets or Sets IsRecievingLocationCapacityExceed
        /// </summary>
        [DataMember(Name="isRecievingLocationCapacityExceed")]
        public bool? IsRecievingLocationCapacityExceed { get; set; }

        /// <summary>
        /// Gets or Sets IsSelfCollect
        /// </summary>
        [DataMember(Name="isSelfCollect")]
        public bool? IsSelfCollect { get; set; }

        /// <summary>
        /// Gets or Sets IsSendToWMS
        /// </summary>
        [DataMember(Name="isSendToWMS")]
        public bool? IsSendToWMS { get; set; }

        /// <summary>
        /// Gets or Sets IsSIOI
        /// </summary>
        [DataMember(Name="isSIOI")]
        public long? IsSIOI { get; set; }

        /// <summary>
        /// Gets or Sets IsSTOTUpdated
        /// </summary>
        [DataMember(Name="isSTOTUpdated")]
        public bool? IsSTOTUpdated { get; set; }

        /// <summary>
        /// Gets or Sets IsVatIntegrationProcessed
        /// </summary>
        [DataMember(Name="isVatIntegrationProcessed")]
        public bool? IsVatIntegrationProcessed { get; set; }

        /// <summary>
        /// Gets or Sets LoadNumber
        /// </summary>
        [DataMember(Name="loadNumber")]
        public string LoadNumber { get; set; }

        /// <summary>
        /// Gets or Sets ModeOfDelivery
        /// </summary>
        [DataMember(Name="modeOfDelivery")]
        public string ModeOfDelivery { get; set; }

        /// <summary>
        /// Gets or Sets ModifiedBy
        /// </summary>
        [DataMember(Name="modifiedBy")]
        public long? ModifiedBy { get; set; }

        /// <summary>
        /// Gets or Sets ModifiedDate
        /// </summary>
        [DataMember(Name="modifiedDate")]
        public DateTime? ModifiedDate { get; set; }

        /// <summary>
        /// Gets or Sets NextState
        /// </summary>
        [DataMember(Name="nextState")]
        public long? NextState { get; set; }

        /// <summary>
        /// Gets or Sets NumberOfCrate
        /// </summary>
        [DataMember(Name="numberOfCrate")]
        public long? NumberOfCrate { get; set; }

        /// <summary>
        /// Gets or Sets NumberOfPalettes
        /// </summary>
        [DataMember(Name="numberOfPalettes")]
        public double? NumberOfPalettes { get; set; }

        /// <summary>
        /// Gets or Sets Oi
        /// </summary>
        [DataMember(Name="oi")]
        public string Oi { get; set; }

        /// <summary>
        /// Gets or Sets OrderDate
        /// </summary>
        [DataMember(Name="orderDate")]
        public DateTime? OrderDate { get; set; }

        /// <summary>
        /// Gets or Sets OrderedBy
        /// </summary>
        [DataMember(Name="orderedBy")]
        public string OrderedBy { get; set; }

        /// <summary>
        /// Gets or Sets OrderId
        /// </summary>
        [DataMember(Name="orderId")]
        public long? OrderId { get; set; }

        /// <summary>
        /// Gets or Sets OrderNumber
        /// </summary>
        [DataMember(Name="orderNumber")]
        public string OrderNumber { get; set; }

        /// <summary>
        /// Gets or Sets EnquiryAutoNumber
        /// </summary>
        [DataMember(Name="enquiryAutoNumber")]
        public string EnquiryAutoNumber { get; set; }

        /// <summary>
        /// Gets or Sets ShortCompanyName
        /// </summary>
        [DataMember(Name="shortCompanyName")]
        public string ShortCompanyName { get; set; }

        /// <summary>
        /// Gets or Sets ObjectId
        /// </summary>
        [DataMember(Name="objectId")]
        public long? ObjectId { get; set; }

        /// <summary>
        /// Gets or Sets ObjectNumber
        /// </summary>
        [DataMember(Name="objectNumber")]
        public string ObjectNumber { get; set; }

        /// <summary>
        /// Gets or Sets MarkOrderAsShipped
        /// </summary>
        [DataMember(Name="markOrderAsShipped")]
        public bool? MarkOrderAsShipped { get; set; }

        /// <summary>
        /// Gets or Sets IsCancelOrder
        /// </summary>
        [DataMember(Name="isCancelOrder")]
        public bool? IsCancelOrder { get; set; }

        /// <summary>
        /// Gets or Sets IsRejectDelivery
        /// </summary>
        [DataMember(Name="isRejectDelivery")]
        public bool? IsRejectDelivery { get; set; }

        /// <summary>
        /// Gets or Sets OrderType
        /// </summary>
        [DataMember(Name="orderType")]
        public string OrderType { get; set; }

        /// <summary>
        /// Gets or Sets PalletSpace
        /// </summary>
        [DataMember(Name="palletSpace")]
        public double? PalletSpace { get; set; }

        /// <summary>
        /// Gets or Sets TruckCapacityPalettes
        /// </summary>
        [DataMember(Name="truckCapacityPalettes")]
        public double? TruckCapacityPalettes { get; set; }

        /// <summary>
        /// Gets or Sets TruckCapacityWeight
        /// </summary>
        [DataMember(Name="truckCapacityWeight")]
        public double? TruckCapacityWeight { get; set; }

        /// <summary>
        /// Gets or Sets ParentOrderId
        /// </summary>
        [DataMember(Name="parentOrderId")]
        public long? ParentOrderId { get; set; }

        /// <summary>
        /// Gets or Sets PaymentTerm
        /// </summary>
        [DataMember(Name="paymentTerm")]
        public long? PaymentTerm { get; set; }

        /// <summary>
        /// Gets or Sets PickDateTime
        /// </summary>
        [DataMember(Name="pickDateTime")]
        public DateTime? PickDateTime { get; set; }

        /// <summary>
        /// Gets or Sets PickNumber
        /// </summary>
        [DataMember(Name="pickNumber")]
        public string PickNumber { get; set; }

        /// <summary>
        /// Gets or Sets PresellerCode
        /// </summary>
        [DataMember(Name="presellerCode")]
        public string PresellerCode { get; set; }

        /// <summary>
        /// Gets or Sets PresellerName
        /// </summary>
        [DataMember(Name="presellerName")]
        public string PresellerName { get; set; }

        /// <summary>
        /// Gets or Sets PreviousState
        /// </summary>
        [DataMember(Name="previousState")]
        public long? PreviousState { get; set; }

        /// <summary>
        /// Gets or Sets PrimaryAddress
        /// </summary>
        [DataMember(Name="primaryAddress")]
        public string PrimaryAddress { get; set; }

        /// <summary>
        /// Gets or Sets PrimaryAddressId
        /// </summary>
        [DataMember(Name="primaryAddressId")]
        public long? PrimaryAddressId { get; set; }

        /// <summary>
        /// Gets or Sets Province
        /// </summary>
        [DataMember(Name="province")]
        public string Province { get; set; }

        /// <summary>
        /// Gets or Sets PurchaseOrderNumber
        /// </summary>
        [DataMember(Name="purchaseOrderNumber")]
        public string PurchaseOrderNumber { get; set; }

        /// <summary>
        /// Gets or Sets RedInvoiceNumber
        /// </summary>
        [DataMember(Name="redInvoiceNumber")]
        public string RedInvoiceNumber { get; set; }

        /// <summary>
        /// Gets or Sets ReferenceForSIOI
        /// </summary>
        [DataMember(Name="referenceForSIOI")]
        public string ReferenceForSIOI { get; set; }

        /// <summary>
        /// Gets or Sets ReferenceNumber
        /// </summary>
        [DataMember(Name="referenceNumber")]
        public string ReferenceNumber { get; set; }

        /// <summary>
        /// Gets or Sets Remarks
        /// </summary>
        [DataMember(Name="remarks")]
        public string Remarks { get; set; }

        /// <summary>
        /// Gets or Sets SalesOrderNumber
        /// </summary>
        [DataMember(Name="salesOrderNumber")]
        public string SalesOrderNumber { get; set; }

        /// <summary>
        /// Gets or Sets SecondaryAddress
        /// </summary>
        [DataMember(Name="secondaryAddress")]
        public string SecondaryAddress { get; set; }

        /// <summary>
        /// Gets or Sets SecondaryAddressId
        /// </summary>
        [DataMember(Name="secondaryAddressId")]
        public long? SecondaryAddressId { get; set; }

        /// <summary>
        /// Gets or Sets SequenceNo
        /// </summary>
        [DataMember(Name="sequenceNo")]
        public long? SequenceNo { get; set; }

        /// <summary>
        /// Gets or Sets ShipTo
        /// </summary>
        [DataMember(Name="shipTo")]
        public long? ShipTo { get; set; }

        /// <summary>
        /// Gets or Sets ShipToCode
        /// </summary>
        [DataMember(Name="shipToCode")]
        public string ShipToCode { get; set; }

        /// <summary>
        /// Gets or Sets ShipToName
        /// </summary>
        [DataMember(Name="shipToName")]
        public string ShipToName { get; set; }

        /// <summary>
        /// Gets or Sets ShipToLocationAddress
        /// </summary>
        [DataMember(Name="shipToLocationAddress")]
        public string ShipToLocationAddress { get; set; }

        /// <summary>
        /// Gets or Sets Area
        /// </summary>
        [DataMember(Name="area")]
        public string Area { get; set; }

        /// <summary>
        /// Gets or Sets Si
        /// </summary>
        [DataMember(Name="si")]
        public string Si { get; set; }

        /// <summary>
        /// Gets or Sets SoldTo
        /// </summary>
        [DataMember(Name="soldTo")]
        public long? SoldTo { get; set; }

        /// <summary>
        /// Gets or Sets SoldToCode
        /// </summary>
        [DataMember(Name="soldToCode")]
        public string SoldToCode { get; set; }

        /// <summary>
        /// Gets or Sets SoldToName
        /// </summary>
        [DataMember(Name="soldToName")]
        public string SoldToName { get; set; }

        /// <summary>
        /// Gets or Sets StockLocationId
        /// </summary>
        [DataMember(Name="stockLocationId")]
        public string StockLocationId { get; set; }

        /// <summary>
        /// Gets or Sets TotalAmount
        /// </summary>
        [DataMember(Name="totalAmount")]
        public double? TotalAmount { get; set; }

        /// <summary>
        /// Gets or Sets TotalDepositeAmount
        /// </summary>
        [DataMember(Name="totalDepositeAmount")]
        public double? TotalDepositeAmount { get; set; }

        /// <summary>
        /// Gets or Sets TotalDiscountAmount
        /// </summary>
        [DataMember(Name="totalDiscountAmount")]
        public double? TotalDiscountAmount { get; set; }

        /// <summary>
        /// Gets or Sets TotalPrice
        /// </summary>
        [DataMember(Name="totalPrice")]
        public double? TotalPrice { get; set; }

        /// <summary>
        /// Gets or Sets TotalQuantity
        /// </summary>
        [DataMember(Name="totalQuantity")]
        public double? TotalQuantity { get; set; }

        /// <summary>
        /// Gets or Sets TotalTaxAmount
        /// </summary>
        [DataMember(Name="totalTaxAmount")]
        public double? TotalTaxAmount { get; set; }

        /// <summary>
        /// Gets or Sets TotalVolume
        /// </summary>
        [DataMember(Name="totalVolume")]
        public double? TotalVolume { get; set; }

        /// <summary>
        /// Gets or Sets TotalValue
        /// </summary>
        [DataMember(Name="totalValue")]
        public double? TotalValue { get; set; }

        /// <summary>
        /// Gets or Sets TotalWeight
        /// </summary>
        [DataMember(Name="totalWeight")]
        public double? TotalWeight { get; set; }

        /// <summary>
        /// Gets or Sets TruckBranchPlantLocationId
        /// </summary>
        [DataMember(Name="truckBranchPlantLocationId")]
        public long? TruckBranchPlantLocationId { get; set; }

        /// <summary>
        /// Gets or Sets TruckSize
        /// </summary>
        [DataMember(Name="truckSize")]
        public string TruckSize { get; set; }

        /// <summary>
        /// Gets or Sets TruckSizeId
        /// </summary>
        [DataMember(Name="truckSizeId")]
        public long? TruckSizeId { get; set; }

        /// <summary>
        /// Gets or Sets TruckWeight
        /// </summary>
        [DataMember(Name="truckWeight")]
        public double? TruckWeight { get; set; }

        /// <summary>
        /// Gets or Sets PageIndex
        /// </summary>
        [DataMember(Name="pageIndex")]
        public int? PageIndex { get; set; }

        /// <summary>
        /// Gets or Sets PageSize
        /// </summary>
        [DataMember(Name="pageSize")]
        public int? PageSize { get; set; }

        /// <summary>
        /// Gets or Sets RoleId
        /// </summary>
        [DataMember(Name="roleId")]
        public long? RoleId { get; set; }

        /// <summary>
        /// Gets or Sets TotalCount
        /// </summary>
        [DataMember(Name="totalCount")]
        public long? TotalCount { get; set; }

        /// <summary>
        /// Gets or Sets Class
        /// </summary>
        [DataMember(Name="class")]
        public string Class { get; set; }

        /// <summary>
        /// Gets or Sets IsPartialReceive
        /// </summary>
        [DataMember(Name="isPartialReceive")]
        public bool? IsPartialReceive { get; set; }

        /// <summary>
        /// Gets or Sets IsReceive
        /// </summary>
        [DataMember(Name="isReceive")]
        public bool? IsReceive { get; set; }

        /// <summary>
        /// Gets or Sets LastSyncDate
        /// </summary>
        [DataMember(Name="lastSyncDate")]
        public DateTime? LastSyncDate { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets RejectionReasonCode
        /// </summary>
        [DataMember(Name="rejectionReasonCode")]
        public string RejectionReasonCode { get; set; }

        /// <summary>
        /// Gets or Sets RejectionComment
        /// </summary>
        [DataMember(Name="rejectionComment")]
        public string RejectionComment { get; set; }

        /// <summary>
        /// Gets or Sets ReceivedBy
        /// </summary>
        [DataMember(Name="receivedBy")]
        public string ReceivedBy { get; set; }

        /// <summary>
        /// Gets or Sets Coordinates
        /// </summary>
        [DataMember(Name="coordinates")]
        public string Coordinates { get; set; }

        /// <summary>
        /// Gets or Sets ReceivedDate
        /// </summary>
        [DataMember(Name="receivedDate")]
        public DateTime? ReceivedDate { get; set; }

        /// <summary>
        /// Gets or Sets OrderShippedDate
        /// </summary>
        [DataMember(Name="orderShippedDate")]
        public DateTime? OrderShippedDate { get; set; }

        /// <summary>
        /// Gets or Sets RelatedOrderId
        /// </summary>
        [DataMember(Name="relatedOrderId")]
        public long? RelatedOrderId { get; set; }

        /// <summary>
        /// Gets or Sets RelatedOrderNumber
        /// </summary>
        [DataMember(Name="relatedOrderNumber")]
        public string RelatedOrderNumber { get; set; }

        /// <summary>
        /// Gets or Sets TypeOfWay
        /// </summary>
        [DataMember(Name="typeOfWay")]
        public string TypeOfWay { get; set; }

        /// <summary>
        /// Gets or Sets IsAnyItemPriceZero
        /// </summary>
        [DataMember(Name="isAnyItemPriceZero")]
        public long? IsAnyItemPriceZero { get; set; }

        /// <summary>
        /// Gets or Sets OrderList
        /// </summary>
        [DataMember(Name="orderList")]
        public Collection<GlassRUNServiceWebApiManageOrderDTOOrderDTO> OrderList { get; set; }

        /// <summary>
        /// Gets or Sets OrderProductList
        /// </summary>
        [DataMember(Name="orderProductList")]
        public Collection<GlassRUNServiceWebApiManageOrderDTOOrderProductDTO> OrderProductList { get; set; }

        /// <summary>
        /// Gets or Sets NoteList
        /// </summary>
        [DataMember(Name="noteList")]
        public Collection<GlassRUNServiceWebApiManageOrderDTONoteDTO> NoteList { get; set; }

        /// <summary>
        /// Gets or Sets OrderDocumentList
        /// </summary>
        [DataMember(Name="orderDocumentList")]
        public Collection<GlassRUNServiceWebApiManageOrderDTOOrderDocumentDTO> OrderDocumentList { get; set; }

        /// <summary>
        /// Gets or Sets ReasonCodeList
        /// </summary>
        [DataMember(Name="reasonCodeList")]
        public Collection<GlassRUNServiceWebApiManageOrderDTOReasonCodeDTO> ReasonCodeList { get; set; }

        /// <summary>
        /// Gets or Sets OrderProductMovementList
        /// </summary>
        [DataMember(Name="orderProductMovementList")]
        public Collection<GlassRUNServiceWebApiManageOrderDTOOrderProductMovementDTO> OrderProductMovementList { get; set; }

        /// <summary>
        /// Gets or Sets OrderFeedbackList
        /// </summary>
        [DataMember(Name="orderFeedbackList")]
        public Collection<GlassRUNServiceWebApiManageOrderDTOOrderFeedbackDTO> OrderFeedbackList { get; set; }

        /// <summary>
        /// Gets or Sets SurveyFormList
        /// </summary>
        [DataMember(Name="surveyFormList")]
        public Collection<GlassRUNServiceWebApiManageOrderDTOSurveyFormDTO> SurveyFormList { get; set; }

        /// <summary>
        /// Gets or Sets SubChannel
        /// </summary>
        [DataMember(Name="subChannel")]
        public string SubChannel { get; set; }

        /// <summary>
        /// Gets or Sets IsSOAttached
        /// </summary>
        [DataMember(Name="isSOAttached")]
        public bool? IsSOAttached { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GlassRUNServiceWebApiManageOrderDTOOrderDTO {\n");
            sb.Append("  BillTo: ").Append(BillTo).Append("\n");
            sb.Append("  BillToCode: ").Append(BillToCode).Append("\n");
            sb.Append("  DriverName: ").Append(DriverName).Append("\n");
            sb.Append("  PlateNumber: ").Append(PlateNumber).Append("\n");
            sb.Append("  BillToName: ").Append(BillToName).Append("\n");
            sb.Append("  WorkFlowCode: ").Append(WorkFlowCode).Append("\n");
            sb.Append("  CarrierCode: ").Append(CarrierCode).Append("\n");
            sb.Append("  CarrierETA: ").Append(CarrierETA).Append("\n");
            sb.Append("  CarrierETD: ").Append(CarrierETD).Append("\n");
            sb.Append("  CarrierName: ").Append(CarrierName).Append("\n");
            sb.Append("  CarrierNumber: ").Append(CarrierNumber).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  PriorityValue: ").Append(PriorityValue).Append("\n");
            sb.Append("  LoginId: ").Append(LoginId).Append("\n");
            sb.Append("  CollectionLocationCode: ").Append(CollectionLocationCode).Append("\n");
            sb.Append("  CollectionLocationId: ").Append(CollectionLocationId).Append("\n");
            sb.Append("  CollectionLocationName: ").Append(CollectionLocationName).Append("\n");
            sb.Append("  CompanyCode: ").Append(CompanyCode).Append("\n");
            sb.Append("  CompanyName: ").Append(CompanyName).Append("\n");
            sb.Append("  CompanyId: ").Append(CompanyId).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  CreatedDate: ").Append(CreatedDate).Append("\n");
            sb.Append("  CurrentState: ").Append(CurrentState).Append("\n");
            sb.Append("  Description1: ").Append(Description1).Append("\n");
            sb.Append("  Description2: ").Append(Description2).Append("\n");
            sb.Append("  DiscountAmount: ").Append(DiscountAmount).Append("\n");
            sb.Append("  DiscountPercent: ").Append(DiscountPercent).Append("\n");
            sb.Append("  EnquiryId: ").Append(EnquiryId).Append("\n");
            sb.Append("  ExpectedTimeOfDelivery: ").Append(ExpectedTimeOfDelivery).Append("\n");
            sb.Append("  Field1: ").Append(Field1).Append("\n");
            sb.Append("  Field10: ").Append(Field10).Append("\n");
            sb.Append("  Field2: ").Append(Field2).Append("\n");
            sb.Append("  Field3: ").Append(Field3).Append("\n");
            sb.Append("  Field4: ").Append(Field4).Append("\n");
            sb.Append("  Field5: ").Append(Field5).Append("\n");
            sb.Append("  Field6: ").Append(Field6).Append("\n");
            sb.Append("  Field7: ").Append(Field7).Append("\n");
            sb.Append("  Field8: ").Append(Field8).Append("\n");
            sb.Append("  Field9: ").Append(Field9).Append("\n");
            sb.Append("  GratisCode: ").Append(GratisCode).Append("\n");
            sb.Append("  HoldStatus: ").Append(HoldStatus).Append("\n");
            sb.Append("  InvoiceNumber: ").Append(InvoiceNumber).Append("\n");
            sb.Append("  EInvoiceNumber: ").Append(EInvoiceNumber).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  IsAdhoc: ").Append(IsAdhoc).Append("\n");
            sb.Append("  IsInventoryTransfer: ").Append(IsInventoryTransfer).Append("\n");
            sb.Append("  IsLockFromWMS: ").Append(IsLockFromWMS).Append("\n");
            sb.Append("  IsPickConfirmed: ").Append(IsPickConfirmed).Append("\n");
            sb.Append("  IsPrintPickSlip: ").Append(IsPrintPickSlip).Append("\n");
            sb.Append("  IsRecievingLocationCapacityExceed: ").Append(IsRecievingLocationCapacityExceed).Append("\n");
            sb.Append("  IsSelfCollect: ").Append(IsSelfCollect).Append("\n");
            sb.Append("  IsSendToWMS: ").Append(IsSendToWMS).Append("\n");
            sb.Append("  IsSIOI: ").Append(IsSIOI).Append("\n");
            sb.Append("  IsSTOTUpdated: ").Append(IsSTOTUpdated).Append("\n");
            sb.Append("  IsVatIntegrationProcessed: ").Append(IsVatIntegrationProcessed).Append("\n");
            sb.Append("  LoadNumber: ").Append(LoadNumber).Append("\n");
            sb.Append("  ModeOfDelivery: ").Append(ModeOfDelivery).Append("\n");
            sb.Append("  ModifiedBy: ").Append(ModifiedBy).Append("\n");
            sb.Append("  ModifiedDate: ").Append(ModifiedDate).Append("\n");
            sb.Append("  NextState: ").Append(NextState).Append("\n");
            sb.Append("  NumberOfCrate: ").Append(NumberOfCrate).Append("\n");
            sb.Append("  NumberOfPalettes: ").Append(NumberOfPalettes).Append("\n");
            sb.Append("  Oi: ").Append(Oi).Append("\n");
            sb.Append("  OrderDate: ").Append(OrderDate).Append("\n");
            sb.Append("  OrderedBy: ").Append(OrderedBy).Append("\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  OrderNumber: ").Append(OrderNumber).Append("\n");
            sb.Append("  EnquiryAutoNumber: ").Append(EnquiryAutoNumber).Append("\n");
            sb.Append("  ShortCompanyName: ").Append(ShortCompanyName).Append("\n");
            sb.Append("  ObjectId: ").Append(ObjectId).Append("\n");
            sb.Append("  ObjectNumber: ").Append(ObjectNumber).Append("\n");
            sb.Append("  MarkOrderAsShipped: ").Append(MarkOrderAsShipped).Append("\n");
            sb.Append("  IsCancelOrder: ").Append(IsCancelOrder).Append("\n");
            sb.Append("  IsRejectDelivery: ").Append(IsRejectDelivery).Append("\n");
            sb.Append("  OrderType: ").Append(OrderType).Append("\n");
            sb.Append("  PalletSpace: ").Append(PalletSpace).Append("\n");
            sb.Append("  TruckCapacityPalettes: ").Append(TruckCapacityPalettes).Append("\n");
            sb.Append("  TruckCapacityWeight: ").Append(TruckCapacityWeight).Append("\n");
            sb.Append("  ParentOrderId: ").Append(ParentOrderId).Append("\n");
            sb.Append("  PaymentTerm: ").Append(PaymentTerm).Append("\n");
            sb.Append("  PickDateTime: ").Append(PickDateTime).Append("\n");
            sb.Append("  PickNumber: ").Append(PickNumber).Append("\n");
            sb.Append("  PresellerCode: ").Append(PresellerCode).Append("\n");
            sb.Append("  PresellerName: ").Append(PresellerName).Append("\n");
            sb.Append("  PreviousState: ").Append(PreviousState).Append("\n");
            sb.Append("  PrimaryAddress: ").Append(PrimaryAddress).Append("\n");
            sb.Append("  PrimaryAddressId: ").Append(PrimaryAddressId).Append("\n");
            sb.Append("  Province: ").Append(Province).Append("\n");
            sb.Append("  PurchaseOrderNumber: ").Append(PurchaseOrderNumber).Append("\n");
            sb.Append("  RedInvoiceNumber: ").Append(RedInvoiceNumber).Append("\n");
            sb.Append("  ReferenceForSIOI: ").Append(ReferenceForSIOI).Append("\n");
            sb.Append("  ReferenceNumber: ").Append(ReferenceNumber).Append("\n");
            sb.Append("  Remarks: ").Append(Remarks).Append("\n");
            sb.Append("  SalesOrderNumber: ").Append(SalesOrderNumber).Append("\n");
            sb.Append("  SecondaryAddress: ").Append(SecondaryAddress).Append("\n");
            sb.Append("  SecondaryAddressId: ").Append(SecondaryAddressId).Append("\n");
            sb.Append("  SequenceNo: ").Append(SequenceNo).Append("\n");
            sb.Append("  ShipTo: ").Append(ShipTo).Append("\n");
            sb.Append("  ShipToCode: ").Append(ShipToCode).Append("\n");
            sb.Append("  ShipToName: ").Append(ShipToName).Append("\n");
            sb.Append("  ShipToLocationAddress: ").Append(ShipToLocationAddress).Append("\n");
            sb.Append("  Area: ").Append(Area).Append("\n");
            sb.Append("  Si: ").Append(Si).Append("\n");
            sb.Append("  SoldTo: ").Append(SoldTo).Append("\n");
            sb.Append("  SoldToCode: ").Append(SoldToCode).Append("\n");
            sb.Append("  SoldToName: ").Append(SoldToName).Append("\n");
            sb.Append("  StockLocationId: ").Append(StockLocationId).Append("\n");
            sb.Append("  TotalAmount: ").Append(TotalAmount).Append("\n");
            sb.Append("  TotalDepositeAmount: ").Append(TotalDepositeAmount).Append("\n");
            sb.Append("  TotalDiscountAmount: ").Append(TotalDiscountAmount).Append("\n");
            sb.Append("  TotalPrice: ").Append(TotalPrice).Append("\n");
            sb.Append("  TotalQuantity: ").Append(TotalQuantity).Append("\n");
            sb.Append("  TotalTaxAmount: ").Append(TotalTaxAmount).Append("\n");
            sb.Append("  TotalVolume: ").Append(TotalVolume).Append("\n");
            sb.Append("  TotalValue: ").Append(TotalValue).Append("\n");
            sb.Append("  TotalWeight: ").Append(TotalWeight).Append("\n");
            sb.Append("  TruckBranchPlantLocationId: ").Append(TruckBranchPlantLocationId).Append("\n");
            sb.Append("  TruckSize: ").Append(TruckSize).Append("\n");
            sb.Append("  TruckSizeId: ").Append(TruckSizeId).Append("\n");
            sb.Append("  TruckWeight: ").Append(TruckWeight).Append("\n");
            sb.Append("  PageIndex: ").Append(PageIndex).Append("\n");
            sb.Append("  PageSize: ").Append(PageSize).Append("\n");
            sb.Append("  RoleId: ").Append(RoleId).Append("\n");
            sb.Append("  TotalCount: ").Append(TotalCount).Append("\n");
            sb.Append("  Class: ").Append(Class).Append("\n");
            sb.Append("  IsPartialReceive: ").Append(IsPartialReceive).Append("\n");
            sb.Append("  IsReceive: ").Append(IsReceive).Append("\n");
            sb.Append("  LastSyncDate: ").Append(LastSyncDate).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  RejectionReasonCode: ").Append(RejectionReasonCode).Append("\n");
            sb.Append("  RejectionComment: ").Append(RejectionComment).Append("\n");
            sb.Append("  ReceivedBy: ").Append(ReceivedBy).Append("\n");
            sb.Append("  Coordinates: ").Append(Coordinates).Append("\n");
            sb.Append("  ReceivedDate: ").Append(ReceivedDate).Append("\n");
            sb.Append("  OrderShippedDate: ").Append(OrderShippedDate).Append("\n");
            sb.Append("  RelatedOrderId: ").Append(RelatedOrderId).Append("\n");
            sb.Append("  RelatedOrderNumber: ").Append(RelatedOrderNumber).Append("\n");
            sb.Append("  TypeOfWay: ").Append(TypeOfWay).Append("\n");
            sb.Append("  IsAnyItemPriceZero: ").Append(IsAnyItemPriceZero).Append("\n");
            sb.Append("  OrderList: ").Append(OrderList).Append("\n");
            sb.Append("  OrderProductList: ").Append(OrderProductList).Append("\n");
            sb.Append("  NoteList: ").Append(NoteList).Append("\n");
            sb.Append("  OrderDocumentList: ").Append(OrderDocumentList).Append("\n");
            sb.Append("  ReasonCodeList: ").Append(ReasonCodeList).Append("\n");
            sb.Append("  OrderProductMovementList: ").Append(OrderProductMovementList).Append("\n");
            sb.Append("  OrderFeedbackList: ").Append(OrderFeedbackList).Append("\n");
            sb.Append("  SurveyFormList: ").Append(SurveyFormList).Append("\n");
            sb.Append("  SubChannel: ").Append(SubChannel).Append("\n");
            sb.Append("  IsSOAttached: ").Append(IsSOAttached).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GlassRUNServiceWebApiManageOrderDTOOrderDTO)obj);
        }

        /// <summary>
        /// Returns true if GlassRUNServiceWebApiManageOrderDTOOrderDTO instances are equal
        /// </summary>
        /// <param name="other">Instance of GlassRUNServiceWebApiManageOrderDTOOrderDTO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GlassRUNServiceWebApiManageOrderDTOOrderDTO other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    BillTo == other.BillTo ||
                    BillTo != null &&
                    BillTo.Equals(other.BillTo)
                ) && 
                (
                    BillToCode == other.BillToCode ||
                    BillToCode != null &&
                    BillToCode.Equals(other.BillToCode)
                ) && 
                (
                    DriverName == other.DriverName ||
                    DriverName != null &&
                    DriverName.Equals(other.DriverName)
                ) && 
                (
                    PlateNumber == other.PlateNumber ||
                    PlateNumber != null &&
                    PlateNumber.Equals(other.PlateNumber)
                ) && 
                (
                    BillToName == other.BillToName ||
                    BillToName != null &&
                    BillToName.Equals(other.BillToName)
                ) && 
                (
                    WorkFlowCode == other.WorkFlowCode ||
                    WorkFlowCode != null &&
                    WorkFlowCode.Equals(other.WorkFlowCode)
                ) && 
                (
                    CarrierCode == other.CarrierCode ||
                    CarrierCode != null &&
                    CarrierCode.Equals(other.CarrierCode)
                ) && 
                (
                    CarrierETA == other.CarrierETA ||
                    CarrierETA != null &&
                    CarrierETA.Equals(other.CarrierETA)
                ) && 
                (
                    CarrierETD == other.CarrierETD ||
                    CarrierETD != null &&
                    CarrierETD.Equals(other.CarrierETD)
                ) && 
                (
                    CarrierName == other.CarrierName ||
                    CarrierName != null &&
                    CarrierName.Equals(other.CarrierName)
                ) && 
                (
                    CarrierNumber == other.CarrierNumber ||
                    CarrierNumber != null &&
                    CarrierNumber.Equals(other.CarrierNumber)
                ) && 
                (
                    Priority == other.Priority ||
                    Priority != null &&
                    Priority.Equals(other.Priority)
                ) && 
                (
                    PriorityValue == other.PriorityValue ||
                    PriorityValue != null &&
                    PriorityValue.Equals(other.PriorityValue)
                ) && 
                (
                    LoginId == other.LoginId ||
                    LoginId != null &&
                    LoginId.Equals(other.LoginId)
                ) && 
                (
                    CollectionLocationCode == other.CollectionLocationCode ||
                    CollectionLocationCode != null &&
                    CollectionLocationCode.Equals(other.CollectionLocationCode)
                ) && 
                (
                    CollectionLocationId == other.CollectionLocationId ||
                    CollectionLocationId != null &&
                    CollectionLocationId.Equals(other.CollectionLocationId)
                ) && 
                (
                    CollectionLocationName == other.CollectionLocationName ||
                    CollectionLocationName != null &&
                    CollectionLocationName.Equals(other.CollectionLocationName)
                ) && 
                (
                    CompanyCode == other.CompanyCode ||
                    CompanyCode != null &&
                    CompanyCode.Equals(other.CompanyCode)
                ) && 
                (
                    CompanyName == other.CompanyName ||
                    CompanyName != null &&
                    CompanyName.Equals(other.CompanyName)
                ) && 
                (
                    CompanyId == other.CompanyId ||
                    CompanyId != null &&
                    CompanyId.Equals(other.CompanyId)
                ) && 
                (
                    CreatedBy == other.CreatedBy ||
                    CreatedBy != null &&
                    CreatedBy.Equals(other.CreatedBy)
                ) && 
                (
                    CreatedDate == other.CreatedDate ||
                    CreatedDate != null &&
                    CreatedDate.Equals(other.CreatedDate)
                ) && 
                (
                    CurrentState == other.CurrentState ||
                    CurrentState != null &&
                    CurrentState.Equals(other.CurrentState)
                ) && 
                (
                    Description1 == other.Description1 ||
                    Description1 != null &&
                    Description1.Equals(other.Description1)
                ) && 
                (
                    Description2 == other.Description2 ||
                    Description2 != null &&
                    Description2.Equals(other.Description2)
                ) && 
                (
                    DiscountAmount == other.DiscountAmount ||
                    DiscountAmount != null &&
                    DiscountAmount.Equals(other.DiscountAmount)
                ) && 
                (
                    DiscountPercent == other.DiscountPercent ||
                    DiscountPercent != null &&
                    DiscountPercent.Equals(other.DiscountPercent)
                ) && 
                (
                    EnquiryId == other.EnquiryId ||
                    EnquiryId != null &&
                    EnquiryId.Equals(other.EnquiryId)
                ) && 
                (
                    ExpectedTimeOfDelivery == other.ExpectedTimeOfDelivery ||
                    ExpectedTimeOfDelivery != null &&
                    ExpectedTimeOfDelivery.Equals(other.ExpectedTimeOfDelivery)
                ) && 
                (
                    Field1 == other.Field1 ||
                    Field1 != null &&
                    Field1.Equals(other.Field1)
                ) && 
                (
                    Field10 == other.Field10 ||
                    Field10 != null &&
                    Field10.Equals(other.Field10)
                ) && 
                (
                    Field2 == other.Field2 ||
                    Field2 != null &&
                    Field2.Equals(other.Field2)
                ) && 
                (
                    Field3 == other.Field3 ||
                    Field3 != null &&
                    Field3.Equals(other.Field3)
                ) && 
                (
                    Field4 == other.Field4 ||
                    Field4 != null &&
                    Field4.Equals(other.Field4)
                ) && 
                (
                    Field5 == other.Field5 ||
                    Field5 != null &&
                    Field5.Equals(other.Field5)
                ) && 
                (
                    Field6 == other.Field6 ||
                    Field6 != null &&
                    Field6.Equals(other.Field6)
                ) && 
                (
                    Field7 == other.Field7 ||
                    Field7 != null &&
                    Field7.Equals(other.Field7)
                ) && 
                (
                    Field8 == other.Field8 ||
                    Field8 != null &&
                    Field8.Equals(other.Field8)
                ) && 
                (
                    Field9 == other.Field9 ||
                    Field9 != null &&
                    Field9.Equals(other.Field9)
                ) && 
                (
                    GratisCode == other.GratisCode ||
                    GratisCode != null &&
                    GratisCode.Equals(other.GratisCode)
                ) && 
                (
                    HoldStatus == other.HoldStatus ||
                    HoldStatus != null &&
                    HoldStatus.Equals(other.HoldStatus)
                ) && 
                (
                    InvoiceNumber == other.InvoiceNumber ||
                    InvoiceNumber != null &&
                    InvoiceNumber.Equals(other.InvoiceNumber)
                ) && 
                (
                    EInvoiceNumber == other.EInvoiceNumber ||
                    EInvoiceNumber != null &&
                    EInvoiceNumber.Equals(other.EInvoiceNumber)
                ) && 
                (
                    IsActive == other.IsActive ||
                    IsActive != null &&
                    IsActive.Equals(other.IsActive)
                ) && 
                (
                    IsAdhoc == other.IsAdhoc ||
                    IsAdhoc != null &&
                    IsAdhoc.Equals(other.IsAdhoc)
                ) && 
                (
                    IsInventoryTransfer == other.IsInventoryTransfer ||
                    IsInventoryTransfer != null &&
                    IsInventoryTransfer.Equals(other.IsInventoryTransfer)
                ) && 
                (
                    IsLockFromWMS == other.IsLockFromWMS ||
                    IsLockFromWMS != null &&
                    IsLockFromWMS.Equals(other.IsLockFromWMS)
                ) && 
                (
                    IsPickConfirmed == other.IsPickConfirmed ||
                    IsPickConfirmed != null &&
                    IsPickConfirmed.Equals(other.IsPickConfirmed)
                ) && 
                (
                    IsPrintPickSlip == other.IsPrintPickSlip ||
                    IsPrintPickSlip != null &&
                    IsPrintPickSlip.Equals(other.IsPrintPickSlip)
                ) && 
                (
                    IsRecievingLocationCapacityExceed == other.IsRecievingLocationCapacityExceed ||
                    IsRecievingLocationCapacityExceed != null &&
                    IsRecievingLocationCapacityExceed.Equals(other.IsRecievingLocationCapacityExceed)
                ) && 
                (
                    IsSelfCollect == other.IsSelfCollect ||
                    IsSelfCollect != null &&
                    IsSelfCollect.Equals(other.IsSelfCollect)
                ) && 
                (
                    IsSendToWMS == other.IsSendToWMS ||
                    IsSendToWMS != null &&
                    IsSendToWMS.Equals(other.IsSendToWMS)
                ) && 
                (
                    IsSIOI == other.IsSIOI ||
                    IsSIOI != null &&
                    IsSIOI.Equals(other.IsSIOI)
                ) && 
                (
                    IsSTOTUpdated == other.IsSTOTUpdated ||
                    IsSTOTUpdated != null &&
                    IsSTOTUpdated.Equals(other.IsSTOTUpdated)
                ) && 
                (
                    IsVatIntegrationProcessed == other.IsVatIntegrationProcessed ||
                    IsVatIntegrationProcessed != null &&
                    IsVatIntegrationProcessed.Equals(other.IsVatIntegrationProcessed)
                ) && 
                (
                    LoadNumber == other.LoadNumber ||
                    LoadNumber != null &&
                    LoadNumber.Equals(other.LoadNumber)
                ) && 
                (
                    ModeOfDelivery == other.ModeOfDelivery ||
                    ModeOfDelivery != null &&
                    ModeOfDelivery.Equals(other.ModeOfDelivery)
                ) && 
                (
                    ModifiedBy == other.ModifiedBy ||
                    ModifiedBy != null &&
                    ModifiedBy.Equals(other.ModifiedBy)
                ) && 
                (
                    ModifiedDate == other.ModifiedDate ||
                    ModifiedDate != null &&
                    ModifiedDate.Equals(other.ModifiedDate)
                ) && 
                (
                    NextState == other.NextState ||
                    NextState != null &&
                    NextState.Equals(other.NextState)
                ) && 
                (
                    NumberOfCrate == other.NumberOfCrate ||
                    NumberOfCrate != null &&
                    NumberOfCrate.Equals(other.NumberOfCrate)
                ) && 
                (
                    NumberOfPalettes == other.NumberOfPalettes ||
                    NumberOfPalettes != null &&
                    NumberOfPalettes.Equals(other.NumberOfPalettes)
                ) && 
                (
                    Oi == other.Oi ||
                    Oi != null &&
                    Oi.Equals(other.Oi)
                ) && 
                (
                    OrderDate == other.OrderDate ||
                    OrderDate != null &&
                    OrderDate.Equals(other.OrderDate)
                ) && 
                (
                    OrderedBy == other.OrderedBy ||
                    OrderedBy != null &&
                    OrderedBy.Equals(other.OrderedBy)
                ) && 
                (
                    OrderId == other.OrderId ||
                    OrderId != null &&
                    OrderId.Equals(other.OrderId)
                ) && 
                (
                    OrderNumber == other.OrderNumber ||
                    OrderNumber != null &&
                    OrderNumber.Equals(other.OrderNumber)
                ) && 
                (
                    EnquiryAutoNumber == other.EnquiryAutoNumber ||
                    EnquiryAutoNumber != null &&
                    EnquiryAutoNumber.Equals(other.EnquiryAutoNumber)
                ) && 
                (
                    ShortCompanyName == other.ShortCompanyName ||
                    ShortCompanyName != null &&
                    ShortCompanyName.Equals(other.ShortCompanyName)
                ) && 
                (
                    ObjectId == other.ObjectId ||
                    ObjectId != null &&
                    ObjectId.Equals(other.ObjectId)
                ) && 
                (
                    ObjectNumber == other.ObjectNumber ||
                    ObjectNumber != null &&
                    ObjectNumber.Equals(other.ObjectNumber)
                ) && 
                (
                    MarkOrderAsShipped == other.MarkOrderAsShipped ||
                    MarkOrderAsShipped != null &&
                    MarkOrderAsShipped.Equals(other.MarkOrderAsShipped)
                ) && 
                (
                    IsCancelOrder == other.IsCancelOrder ||
                    IsCancelOrder != null &&
                    IsCancelOrder.Equals(other.IsCancelOrder)
                ) && 
                (
                    IsRejectDelivery == other.IsRejectDelivery ||
                    IsRejectDelivery != null &&
                    IsRejectDelivery.Equals(other.IsRejectDelivery)
                ) && 
                (
                    OrderType == other.OrderType ||
                    OrderType != null &&
                    OrderType.Equals(other.OrderType)
                ) && 
                (
                    PalletSpace == other.PalletSpace ||
                    PalletSpace != null &&
                    PalletSpace.Equals(other.PalletSpace)
                ) && 
                (
                    TruckCapacityPalettes == other.TruckCapacityPalettes ||
                    TruckCapacityPalettes != null &&
                    TruckCapacityPalettes.Equals(other.TruckCapacityPalettes)
                ) && 
                (
                    TruckCapacityWeight == other.TruckCapacityWeight ||
                    TruckCapacityWeight != null &&
                    TruckCapacityWeight.Equals(other.TruckCapacityWeight)
                ) && 
                (
                    ParentOrderId == other.ParentOrderId ||
                    ParentOrderId != null &&
                    ParentOrderId.Equals(other.ParentOrderId)
                ) && 
                (
                    PaymentTerm == other.PaymentTerm ||
                    PaymentTerm != null &&
                    PaymentTerm.Equals(other.PaymentTerm)
                ) && 
                (
                    PickDateTime == other.PickDateTime ||
                    PickDateTime != null &&
                    PickDateTime.Equals(other.PickDateTime)
                ) && 
                (
                    PickNumber == other.PickNumber ||
                    PickNumber != null &&
                    PickNumber.Equals(other.PickNumber)
                ) && 
                (
                    PresellerCode == other.PresellerCode ||
                    PresellerCode != null &&
                    PresellerCode.Equals(other.PresellerCode)
                ) && 
                (
                    PresellerName == other.PresellerName ||
                    PresellerName != null &&
                    PresellerName.Equals(other.PresellerName)
                ) && 
                (
                    PreviousState == other.PreviousState ||
                    PreviousState != null &&
                    PreviousState.Equals(other.PreviousState)
                ) && 
                (
                    PrimaryAddress == other.PrimaryAddress ||
                    PrimaryAddress != null &&
                    PrimaryAddress.Equals(other.PrimaryAddress)
                ) && 
                (
                    PrimaryAddressId == other.PrimaryAddressId ||
                    PrimaryAddressId != null &&
                    PrimaryAddressId.Equals(other.PrimaryAddressId)
                ) && 
                (
                    Province == other.Province ||
                    Province != null &&
                    Province.Equals(other.Province)
                ) && 
                (
                    PurchaseOrderNumber == other.PurchaseOrderNumber ||
                    PurchaseOrderNumber != null &&
                    PurchaseOrderNumber.Equals(other.PurchaseOrderNumber)
                ) && 
                (
                    RedInvoiceNumber == other.RedInvoiceNumber ||
                    RedInvoiceNumber != null &&
                    RedInvoiceNumber.Equals(other.RedInvoiceNumber)
                ) && 
                (
                    ReferenceForSIOI == other.ReferenceForSIOI ||
                    ReferenceForSIOI != null &&
                    ReferenceForSIOI.Equals(other.ReferenceForSIOI)
                ) && 
                (
                    ReferenceNumber == other.ReferenceNumber ||
                    ReferenceNumber != null &&
                    ReferenceNumber.Equals(other.ReferenceNumber)
                ) && 
                (
                    Remarks == other.Remarks ||
                    Remarks != null &&
                    Remarks.Equals(other.Remarks)
                ) && 
                (
                    SalesOrderNumber == other.SalesOrderNumber ||
                    SalesOrderNumber != null &&
                    SalesOrderNumber.Equals(other.SalesOrderNumber)
                ) && 
                (
                    SecondaryAddress == other.SecondaryAddress ||
                    SecondaryAddress != null &&
                    SecondaryAddress.Equals(other.SecondaryAddress)
                ) && 
                (
                    SecondaryAddressId == other.SecondaryAddressId ||
                    SecondaryAddressId != null &&
                    SecondaryAddressId.Equals(other.SecondaryAddressId)
                ) && 
                (
                    SequenceNo == other.SequenceNo ||
                    SequenceNo != null &&
                    SequenceNo.Equals(other.SequenceNo)
                ) && 
                (
                    ShipTo == other.ShipTo ||
                    ShipTo != null &&
                    ShipTo.Equals(other.ShipTo)
                ) && 
                (
                    ShipToCode == other.ShipToCode ||
                    ShipToCode != null &&
                    ShipToCode.Equals(other.ShipToCode)
                ) && 
                (
                    ShipToName == other.ShipToName ||
                    ShipToName != null &&
                    ShipToName.Equals(other.ShipToName)
                ) && 
                (
                    ShipToLocationAddress == other.ShipToLocationAddress ||
                    ShipToLocationAddress != null &&
                    ShipToLocationAddress.Equals(other.ShipToLocationAddress)
                ) && 
                (
                    Area == other.Area ||
                    Area != null &&
                    Area.Equals(other.Area)
                ) && 
                (
                    Si == other.Si ||
                    Si != null &&
                    Si.Equals(other.Si)
                ) && 
                (
                    SoldTo == other.SoldTo ||
                    SoldTo != null &&
                    SoldTo.Equals(other.SoldTo)
                ) && 
                (
                    SoldToCode == other.SoldToCode ||
                    SoldToCode != null &&
                    SoldToCode.Equals(other.SoldToCode)
                ) && 
                (
                    SoldToName == other.SoldToName ||
                    SoldToName != null &&
                    SoldToName.Equals(other.SoldToName)
                ) && 
                (
                    StockLocationId == other.StockLocationId ||
                    StockLocationId != null &&
                    StockLocationId.Equals(other.StockLocationId)
                ) && 
                (
                    TotalAmount == other.TotalAmount ||
                    TotalAmount != null &&
                    TotalAmount.Equals(other.TotalAmount)
                ) && 
                (
                    TotalDepositeAmount == other.TotalDepositeAmount ||
                    TotalDepositeAmount != null &&
                    TotalDepositeAmount.Equals(other.TotalDepositeAmount)
                ) && 
                (
                    TotalDiscountAmount == other.TotalDiscountAmount ||
                    TotalDiscountAmount != null &&
                    TotalDiscountAmount.Equals(other.TotalDiscountAmount)
                ) && 
                (
                    TotalPrice == other.TotalPrice ||
                    TotalPrice != null &&
                    TotalPrice.Equals(other.TotalPrice)
                ) && 
                (
                    TotalQuantity == other.TotalQuantity ||
                    TotalQuantity != null &&
                    TotalQuantity.Equals(other.TotalQuantity)
                ) && 
                (
                    TotalTaxAmount == other.TotalTaxAmount ||
                    TotalTaxAmount != null &&
                    TotalTaxAmount.Equals(other.TotalTaxAmount)
                ) && 
                (
                    TotalVolume == other.TotalVolume ||
                    TotalVolume != null &&
                    TotalVolume.Equals(other.TotalVolume)
                ) && 
                (
                    TotalValue == other.TotalValue ||
                    TotalValue != null &&
                    TotalValue.Equals(other.TotalValue)
                ) && 
                (
                    TotalWeight == other.TotalWeight ||
                    TotalWeight != null &&
                    TotalWeight.Equals(other.TotalWeight)
                ) && 
                (
                    TruckBranchPlantLocationId == other.TruckBranchPlantLocationId ||
                    TruckBranchPlantLocationId != null &&
                    TruckBranchPlantLocationId.Equals(other.TruckBranchPlantLocationId)
                ) && 
                (
                    TruckSize == other.TruckSize ||
                    TruckSize != null &&
                    TruckSize.Equals(other.TruckSize)
                ) && 
                (
                    TruckSizeId == other.TruckSizeId ||
                    TruckSizeId != null &&
                    TruckSizeId.Equals(other.TruckSizeId)
                ) && 
                (
                    TruckWeight == other.TruckWeight ||
                    TruckWeight != null &&
                    TruckWeight.Equals(other.TruckWeight)
                ) && 
                (
                    PageIndex == other.PageIndex ||
                    PageIndex != null &&
                    PageIndex.Equals(other.PageIndex)
                ) && 
                (
                    PageSize == other.PageSize ||
                    PageSize != null &&
                    PageSize.Equals(other.PageSize)
                ) && 
                (
                    RoleId == other.RoleId ||
                    RoleId != null &&
                    RoleId.Equals(other.RoleId)
                ) && 
                (
                    TotalCount == other.TotalCount ||
                    TotalCount != null &&
                    TotalCount.Equals(other.TotalCount)
                ) && 
                (
                    Class == other.Class ||
                    Class != null &&
                    Class.Equals(other.Class)
                ) && 
                (
                    IsPartialReceive == other.IsPartialReceive ||
                    IsPartialReceive != null &&
                    IsPartialReceive.Equals(other.IsPartialReceive)
                ) && 
                (
                    IsReceive == other.IsReceive ||
                    IsReceive != null &&
                    IsReceive.Equals(other.IsReceive)
                ) && 
                (
                    LastSyncDate == other.LastSyncDate ||
                    LastSyncDate != null &&
                    LastSyncDate.Equals(other.LastSyncDate)
                ) && 
                (
                    Status == other.Status ||
                    Status != null &&
                    Status.Equals(other.Status)
                ) && 
                (
                    RejectionReasonCode == other.RejectionReasonCode ||
                    RejectionReasonCode != null &&
                    RejectionReasonCode.Equals(other.RejectionReasonCode)
                ) && 
                (
                    RejectionComment == other.RejectionComment ||
                    RejectionComment != null &&
                    RejectionComment.Equals(other.RejectionComment)
                ) && 
                (
                    ReceivedBy == other.ReceivedBy ||
                    ReceivedBy != null &&
                    ReceivedBy.Equals(other.ReceivedBy)
                ) && 
                (
                    Coordinates == other.Coordinates ||
                    Coordinates != null &&
                    Coordinates.Equals(other.Coordinates)
                ) && 
                (
                    ReceivedDate == other.ReceivedDate ||
                    ReceivedDate != null &&
                    ReceivedDate.Equals(other.ReceivedDate)
                ) && 
                (
                    OrderShippedDate == other.OrderShippedDate ||
                    OrderShippedDate != null &&
                    OrderShippedDate.Equals(other.OrderShippedDate)
                ) && 
                (
                    RelatedOrderId == other.RelatedOrderId ||
                    RelatedOrderId != null &&
                    RelatedOrderId.Equals(other.RelatedOrderId)
                ) && 
                (
                    RelatedOrderNumber == other.RelatedOrderNumber ||
                    RelatedOrderNumber != null &&
                    RelatedOrderNumber.Equals(other.RelatedOrderNumber)
                ) && 
                (
                    TypeOfWay == other.TypeOfWay ||
                    TypeOfWay != null &&
                    TypeOfWay.Equals(other.TypeOfWay)
                ) && 
                (
                    IsAnyItemPriceZero == other.IsAnyItemPriceZero ||
                    IsAnyItemPriceZero != null &&
                    IsAnyItemPriceZero.Equals(other.IsAnyItemPriceZero)
                ) && 
                (
                    OrderList == other.OrderList ||
                    OrderList != null &&
                    OrderList.SequenceEqual(other.OrderList)
                ) && 
                (
                    OrderProductList == other.OrderProductList ||
                    OrderProductList != null &&
                    OrderProductList.SequenceEqual(other.OrderProductList)
                ) && 
                (
                    NoteList == other.NoteList ||
                    NoteList != null &&
                    NoteList.SequenceEqual(other.NoteList)
                ) && 
                (
                    OrderDocumentList == other.OrderDocumentList ||
                    OrderDocumentList != null &&
                    OrderDocumentList.SequenceEqual(other.OrderDocumentList)
                ) && 
                (
                    ReasonCodeList == other.ReasonCodeList ||
                    ReasonCodeList != null &&
                    ReasonCodeList.SequenceEqual(other.ReasonCodeList)
                ) && 
                (
                    OrderProductMovementList == other.OrderProductMovementList ||
                    OrderProductMovementList != null &&
                    OrderProductMovementList.SequenceEqual(other.OrderProductMovementList)
                ) && 
                (
                    OrderFeedbackList == other.OrderFeedbackList ||
                    OrderFeedbackList != null &&
                    OrderFeedbackList.SequenceEqual(other.OrderFeedbackList)
                ) && 
                (
                    SurveyFormList == other.SurveyFormList ||
                    SurveyFormList != null &&
                    SurveyFormList.SequenceEqual(other.SurveyFormList)
                ) && 
                (
                    SubChannel == other.SubChannel ||
                    SubChannel != null &&
                    SubChannel.Equals(other.SubChannel)
                ) && 
                (
                    IsSOAttached == other.IsSOAttached ||
                    IsSOAttached != null &&
                    IsSOAttached.Equals(other.IsSOAttached)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (BillTo != null)
                    hashCode = hashCode * 59 + BillTo.GetHashCode();
                    if (BillToCode != null)
                    hashCode = hashCode * 59 + BillToCode.GetHashCode();
                    if (DriverName != null)
                    hashCode = hashCode * 59 + DriverName.GetHashCode();
                    if (PlateNumber != null)
                    hashCode = hashCode * 59 + PlateNumber.GetHashCode();
                    if (BillToName != null)
                    hashCode = hashCode * 59 + BillToName.GetHashCode();
                    if (WorkFlowCode != null)
                    hashCode = hashCode * 59 + WorkFlowCode.GetHashCode();
                    if (CarrierCode != null)
                    hashCode = hashCode * 59 + CarrierCode.GetHashCode();
                    if (CarrierETA != null)
                    hashCode = hashCode * 59 + CarrierETA.GetHashCode();
                    if (CarrierETD != null)
                    hashCode = hashCode * 59 + CarrierETD.GetHashCode();
                    if (CarrierName != null)
                    hashCode = hashCode * 59 + CarrierName.GetHashCode();
                    if (CarrierNumber != null)
                    hashCode = hashCode * 59 + CarrierNumber.GetHashCode();
                    if (Priority != null)
                    hashCode = hashCode * 59 + Priority.GetHashCode();
                    if (PriorityValue != null)
                    hashCode = hashCode * 59 + PriorityValue.GetHashCode();
                    if (LoginId != null)
                    hashCode = hashCode * 59 + LoginId.GetHashCode();
                    if (CollectionLocationCode != null)
                    hashCode = hashCode * 59 + CollectionLocationCode.GetHashCode();
                    if (CollectionLocationId != null)
                    hashCode = hashCode * 59 + CollectionLocationId.GetHashCode();
                    if (CollectionLocationName != null)
                    hashCode = hashCode * 59 + CollectionLocationName.GetHashCode();
                    if (CompanyCode != null)
                    hashCode = hashCode * 59 + CompanyCode.GetHashCode();
                    if (CompanyName != null)
                    hashCode = hashCode * 59 + CompanyName.GetHashCode();
                    if (CompanyId != null)
                    hashCode = hashCode * 59 + CompanyId.GetHashCode();
                    if (CreatedBy != null)
                    hashCode = hashCode * 59 + CreatedBy.GetHashCode();
                    if (CreatedDate != null)
                    hashCode = hashCode * 59 + CreatedDate.GetHashCode();
                    if (CurrentState != null)
                    hashCode = hashCode * 59 + CurrentState.GetHashCode();
                    if (Description1 != null)
                    hashCode = hashCode * 59 + Description1.GetHashCode();
                    if (Description2 != null)
                    hashCode = hashCode * 59 + Description2.GetHashCode();
                    if (DiscountAmount != null)
                    hashCode = hashCode * 59 + DiscountAmount.GetHashCode();
                    if (DiscountPercent != null)
                    hashCode = hashCode * 59 + DiscountPercent.GetHashCode();
                    if (EnquiryId != null)
                    hashCode = hashCode * 59 + EnquiryId.GetHashCode();
                    if (ExpectedTimeOfDelivery != null)
                    hashCode = hashCode * 59 + ExpectedTimeOfDelivery.GetHashCode();
                    if (Field1 != null)
                    hashCode = hashCode * 59 + Field1.GetHashCode();
                    if (Field10 != null)
                    hashCode = hashCode * 59 + Field10.GetHashCode();
                    if (Field2 != null)
                    hashCode = hashCode * 59 + Field2.GetHashCode();
                    if (Field3 != null)
                    hashCode = hashCode * 59 + Field3.GetHashCode();
                    if (Field4 != null)
                    hashCode = hashCode * 59 + Field4.GetHashCode();
                    if (Field5 != null)
                    hashCode = hashCode * 59 + Field5.GetHashCode();
                    if (Field6 != null)
                    hashCode = hashCode * 59 + Field6.GetHashCode();
                    if (Field7 != null)
                    hashCode = hashCode * 59 + Field7.GetHashCode();
                    if (Field8 != null)
                    hashCode = hashCode * 59 + Field8.GetHashCode();
                    if (Field9 != null)
                    hashCode = hashCode * 59 + Field9.GetHashCode();
                    if (GratisCode != null)
                    hashCode = hashCode * 59 + GratisCode.GetHashCode();
                    if (HoldStatus != null)
                    hashCode = hashCode * 59 + HoldStatus.GetHashCode();
                    if (InvoiceNumber != null)
                    hashCode = hashCode * 59 + InvoiceNumber.GetHashCode();
                    if (EInvoiceNumber != null)
                    hashCode = hashCode * 59 + EInvoiceNumber.GetHashCode();
                    if (IsActive != null)
                    hashCode = hashCode * 59 + IsActive.GetHashCode();
                    if (IsAdhoc != null)
                    hashCode = hashCode * 59 + IsAdhoc.GetHashCode();
                    if (IsInventoryTransfer != null)
                    hashCode = hashCode * 59 + IsInventoryTransfer.GetHashCode();
                    if (IsLockFromWMS != null)
                    hashCode = hashCode * 59 + IsLockFromWMS.GetHashCode();
                    if (IsPickConfirmed != null)
                    hashCode = hashCode * 59 + IsPickConfirmed.GetHashCode();
                    if (IsPrintPickSlip != null)
                    hashCode = hashCode * 59 + IsPrintPickSlip.GetHashCode();
                    if (IsRecievingLocationCapacityExceed != null)
                    hashCode = hashCode * 59 + IsRecievingLocationCapacityExceed.GetHashCode();
                    if (IsSelfCollect != null)
                    hashCode = hashCode * 59 + IsSelfCollect.GetHashCode();
                    if (IsSendToWMS != null)
                    hashCode = hashCode * 59 + IsSendToWMS.GetHashCode();
                    if (IsSIOI != null)
                    hashCode = hashCode * 59 + IsSIOI.GetHashCode();
                    if (IsSTOTUpdated != null)
                    hashCode = hashCode * 59 + IsSTOTUpdated.GetHashCode();
                    if (IsVatIntegrationProcessed != null)
                    hashCode = hashCode * 59 + IsVatIntegrationProcessed.GetHashCode();
                    if (LoadNumber != null)
                    hashCode = hashCode * 59 + LoadNumber.GetHashCode();
                    if (ModeOfDelivery != null)
                    hashCode = hashCode * 59 + ModeOfDelivery.GetHashCode();
                    if (ModifiedBy != null)
                    hashCode = hashCode * 59 + ModifiedBy.GetHashCode();
                    if (ModifiedDate != null)
                    hashCode = hashCode * 59 + ModifiedDate.GetHashCode();
                    if (NextState != null)
                    hashCode = hashCode * 59 + NextState.GetHashCode();
                    if (NumberOfCrate != null)
                    hashCode = hashCode * 59 + NumberOfCrate.GetHashCode();
                    if (NumberOfPalettes != null)
                    hashCode = hashCode * 59 + NumberOfPalettes.GetHashCode();
                    if (Oi != null)
                    hashCode = hashCode * 59 + Oi.GetHashCode();
                    if (OrderDate != null)
                    hashCode = hashCode * 59 + OrderDate.GetHashCode();
                    if (OrderedBy != null)
                    hashCode = hashCode * 59 + OrderedBy.GetHashCode();
                    if (OrderId != null)
                    hashCode = hashCode * 59 + OrderId.GetHashCode();
                    if (OrderNumber != null)
                    hashCode = hashCode * 59 + OrderNumber.GetHashCode();
                    if (EnquiryAutoNumber != null)
                    hashCode = hashCode * 59 + EnquiryAutoNumber.GetHashCode();
                    if (ShortCompanyName != null)
                    hashCode = hashCode * 59 + ShortCompanyName.GetHashCode();
                    if (ObjectId != null)
                    hashCode = hashCode * 59 + ObjectId.GetHashCode();
                    if (ObjectNumber != null)
                    hashCode = hashCode * 59 + ObjectNumber.GetHashCode();
                    if (MarkOrderAsShipped != null)
                    hashCode = hashCode * 59 + MarkOrderAsShipped.GetHashCode();
                    if (IsCancelOrder != null)
                    hashCode = hashCode * 59 + IsCancelOrder.GetHashCode();
                    if (IsRejectDelivery != null)
                    hashCode = hashCode * 59 + IsRejectDelivery.GetHashCode();
                    if (OrderType != null)
                    hashCode = hashCode * 59 + OrderType.GetHashCode();
                    if (PalletSpace != null)
                    hashCode = hashCode * 59 + PalletSpace.GetHashCode();
                    if (TruckCapacityPalettes != null)
                    hashCode = hashCode * 59 + TruckCapacityPalettes.GetHashCode();
                    if (TruckCapacityWeight != null)
                    hashCode = hashCode * 59 + TruckCapacityWeight.GetHashCode();
                    if (ParentOrderId != null)
                    hashCode = hashCode * 59 + ParentOrderId.GetHashCode();
                    if (PaymentTerm != null)
                    hashCode = hashCode * 59 + PaymentTerm.GetHashCode();
                    if (PickDateTime != null)
                    hashCode = hashCode * 59 + PickDateTime.GetHashCode();
                    if (PickNumber != null)
                    hashCode = hashCode * 59 + PickNumber.GetHashCode();
                    if (PresellerCode != null)
                    hashCode = hashCode * 59 + PresellerCode.GetHashCode();
                    if (PresellerName != null)
                    hashCode = hashCode * 59 + PresellerName.GetHashCode();
                    if (PreviousState != null)
                    hashCode = hashCode * 59 + PreviousState.GetHashCode();
                    if (PrimaryAddress != null)
                    hashCode = hashCode * 59 + PrimaryAddress.GetHashCode();
                    if (PrimaryAddressId != null)
                    hashCode = hashCode * 59 + PrimaryAddressId.GetHashCode();
                    if (Province != null)
                    hashCode = hashCode * 59 + Province.GetHashCode();
                    if (PurchaseOrderNumber != null)
                    hashCode = hashCode * 59 + PurchaseOrderNumber.GetHashCode();
                    if (RedInvoiceNumber != null)
                    hashCode = hashCode * 59 + RedInvoiceNumber.GetHashCode();
                    if (ReferenceForSIOI != null)
                    hashCode = hashCode * 59 + ReferenceForSIOI.GetHashCode();
                    if (ReferenceNumber != null)
                    hashCode = hashCode * 59 + ReferenceNumber.GetHashCode();
                    if (Remarks != null)
                    hashCode = hashCode * 59 + Remarks.GetHashCode();
                    if (SalesOrderNumber != null)
                    hashCode = hashCode * 59 + SalesOrderNumber.GetHashCode();
                    if (SecondaryAddress != null)
                    hashCode = hashCode * 59 + SecondaryAddress.GetHashCode();
                    if (SecondaryAddressId != null)
                    hashCode = hashCode * 59 + SecondaryAddressId.GetHashCode();
                    if (SequenceNo != null)
                    hashCode = hashCode * 59 + SequenceNo.GetHashCode();
                    if (ShipTo != null)
                    hashCode = hashCode * 59 + ShipTo.GetHashCode();
                    if (ShipToCode != null)
                    hashCode = hashCode * 59 + ShipToCode.GetHashCode();
                    if (ShipToName != null)
                    hashCode = hashCode * 59 + ShipToName.GetHashCode();
                    if (ShipToLocationAddress != null)
                    hashCode = hashCode * 59 + ShipToLocationAddress.GetHashCode();
                    if (Area != null)
                    hashCode = hashCode * 59 + Area.GetHashCode();
                    if (Si != null)
                    hashCode = hashCode * 59 + Si.GetHashCode();
                    if (SoldTo != null)
                    hashCode = hashCode * 59 + SoldTo.GetHashCode();
                    if (SoldToCode != null)
                    hashCode = hashCode * 59 + SoldToCode.GetHashCode();
                    if (SoldToName != null)
                    hashCode = hashCode * 59 + SoldToName.GetHashCode();
                    if (StockLocationId != null)
                    hashCode = hashCode * 59 + StockLocationId.GetHashCode();
                    if (TotalAmount != null)
                    hashCode = hashCode * 59 + TotalAmount.GetHashCode();
                    if (TotalDepositeAmount != null)
                    hashCode = hashCode * 59 + TotalDepositeAmount.GetHashCode();
                    if (TotalDiscountAmount != null)
                    hashCode = hashCode * 59 + TotalDiscountAmount.GetHashCode();
                    if (TotalPrice != null)
                    hashCode = hashCode * 59 + TotalPrice.GetHashCode();
                    if (TotalQuantity != null)
                    hashCode = hashCode * 59 + TotalQuantity.GetHashCode();
                    if (TotalTaxAmount != null)
                    hashCode = hashCode * 59 + TotalTaxAmount.GetHashCode();
                    if (TotalVolume != null)
                    hashCode = hashCode * 59 + TotalVolume.GetHashCode();
                    if (TotalValue != null)
                    hashCode = hashCode * 59 + TotalValue.GetHashCode();
                    if (TotalWeight != null)
                    hashCode = hashCode * 59 + TotalWeight.GetHashCode();
                    if (TruckBranchPlantLocationId != null)
                    hashCode = hashCode * 59 + TruckBranchPlantLocationId.GetHashCode();
                    if (TruckSize != null)
                    hashCode = hashCode * 59 + TruckSize.GetHashCode();
                    if (TruckSizeId != null)
                    hashCode = hashCode * 59 + TruckSizeId.GetHashCode();
                    if (TruckWeight != null)
                    hashCode = hashCode * 59 + TruckWeight.GetHashCode();
                    if (PageIndex != null)
                    hashCode = hashCode * 59 + PageIndex.GetHashCode();
                    if (PageSize != null)
                    hashCode = hashCode * 59 + PageSize.GetHashCode();
                    if (RoleId != null)
                    hashCode = hashCode * 59 + RoleId.GetHashCode();
                    if (TotalCount != null)
                    hashCode = hashCode * 59 + TotalCount.GetHashCode();
                    if (Class != null)
                    hashCode = hashCode * 59 + Class.GetHashCode();
                    if (IsPartialReceive != null)
                    hashCode = hashCode * 59 + IsPartialReceive.GetHashCode();
                    if (IsReceive != null)
                    hashCode = hashCode * 59 + IsReceive.GetHashCode();
                    if (LastSyncDate != null)
                    hashCode = hashCode * 59 + LastSyncDate.GetHashCode();
                    if (Status != null)
                    hashCode = hashCode * 59 + Status.GetHashCode();
                    if (RejectionReasonCode != null)
                    hashCode = hashCode * 59 + RejectionReasonCode.GetHashCode();
                    if (RejectionComment != null)
                    hashCode = hashCode * 59 + RejectionComment.GetHashCode();
                    if (ReceivedBy != null)
                    hashCode = hashCode * 59 + ReceivedBy.GetHashCode();
                    if (Coordinates != null)
                    hashCode = hashCode * 59 + Coordinates.GetHashCode();
                    if (ReceivedDate != null)
                    hashCode = hashCode * 59 + ReceivedDate.GetHashCode();
                    if (OrderShippedDate != null)
                    hashCode = hashCode * 59 + OrderShippedDate.GetHashCode();
                    if (RelatedOrderId != null)
                    hashCode = hashCode * 59 + RelatedOrderId.GetHashCode();
                    if (RelatedOrderNumber != null)
                    hashCode = hashCode * 59 + RelatedOrderNumber.GetHashCode();
                    if (TypeOfWay != null)
                    hashCode = hashCode * 59 + TypeOfWay.GetHashCode();
                    if (IsAnyItemPriceZero != null)
                    hashCode = hashCode * 59 + IsAnyItemPriceZero.GetHashCode();
                    if (OrderList != null)
                    hashCode = hashCode * 59 + OrderList.GetHashCode();
                    if (OrderProductList != null)
                    hashCode = hashCode * 59 + OrderProductList.GetHashCode();
                    if (NoteList != null)
                    hashCode = hashCode * 59 + NoteList.GetHashCode();
                    if (OrderDocumentList != null)
                    hashCode = hashCode * 59 + OrderDocumentList.GetHashCode();
                    if (ReasonCodeList != null)
                    hashCode = hashCode * 59 + ReasonCodeList.GetHashCode();
                    if (OrderProductMovementList != null)
                    hashCode = hashCode * 59 + OrderProductMovementList.GetHashCode();
                    if (OrderFeedbackList != null)
                    hashCode = hashCode * 59 + OrderFeedbackList.GetHashCode();
                    if (SurveyFormList != null)
                    hashCode = hashCode * 59 + SurveyFormList.GetHashCode();
                    if (SubChannel != null)
                    hashCode = hashCode * 59 + SubChannel.GetHashCode();
                    if (IsSOAttached != null)
                    hashCode = hashCode * 59 + IsSOAttached.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(GlassRUNServiceWebApiManageOrderDTOOrderDTO left, GlassRUNServiceWebApiManageOrderDTOOrderDTO right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(GlassRUNServiceWebApiManageOrderDTOOrderDTO left, GlassRUNServiceWebApiManageOrderDTOOrderDTO right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
