CREATE TABLE [dbo].[EnquiryProductHistory] (
    [EnquiryProductHistoryId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [ReasonCodeId]            BIGINT          NULL,
    [EnquiryProductId]        BIGINT          NULL,
    [EnquiryId]               BIGINT          NOT NULL,
    [ProductCode]             NVARCHAR (200)  NOT NULL,
    [ParentProductCode]       NVARCHAR (200)  NULL,
    [ProductType]             NVARCHAR (200)  NOT NULL,
    [ProductQuantity]         DECIMAL (10, 2) NOT NULL,
    [AvailableQuantity]       DECIMAL (10, 2) NULL,
    [Price]                   DECIMAL (18, 4) NULL,
    [DepositeAmount]          DECIMAL (18, 4) NULL,
    [Remarks]                 NVARCHAR (MAX)  NULL,
    [AssociatedOrder]         NVARCHAR (100)  NULL,
    [CreatedBy]               BIGINT          NOT NULL,
    [CreatedDate]             DATETIME        NOT NULL,
    [ModifiedBy]              BIGINT          NULL,
    [ModifiedDate]            DATETIME        NULL,
    [ItemType]                BIGINT          NULL,
    [IsActive]                BIT             NOT NULL,
    [SequenceNo]              BIGINT          NULL,
    [Field1]                  NVARCHAR (500)  NULL,
    [Field2]                  NVARCHAR (500)  NULL,
    [Field3]                  NVARCHAR (500)  NULL,
    [Field4]                  NVARCHAR (500)  NULL,
    [Field5]                  NVARCHAR (500)  NULL,
    [Field6]                  NVARCHAR (500)  NULL,
    [Field7]                  NVARCHAR (500)  NULL,
    [Field8]                  NVARCHAR (500)  NULL,
    [Field9]                  NVARCHAR (500)  NULL,
    [Field10]                 NVARCHAR (500)  NULL,
    CONSTRAINT [PK_EnquiryProductHistory] PRIMARY KEY CLUSTERED ([EnquiryProductHistoryId] ASC) WITH (FILLFACTOR = 80)
);

