CREATE TABLE [dbo].[FinancePatner] (
    [FinancePatnerId] BIGINT         IDENTITY (1, 1) NOT NULL,
    [FinancerName]    NVARCHAR (500) NOT NULL,
    [AddressLine1]    NVARCHAR (MAX) NULL,
    [AddressLine2]    NVARCHAR (MAX) NULL,
    [AddressLine3]    NVARCHAR (MAX) NULL,
    [City]            NVARCHAR (100) NULL,
    [State]           NVARCHAR (100) NULL,
    [CountryId]       BIGINT         NULL,
    [Country]         NVARCHAR (50)  NULL,
    [Postcode]        NVARCHAR (20)  NULL,
    [CreatedBy]       BIGINT         NOT NULL,
    [CreatedDate]     DATETIME       NOT NULL,
    [ModifiedBy]      BIGINT         NULL,
    [ModifiedDate]    DATETIME       NULL,
    [IsActive]        BIT            NOT NULL,
    [Field1]          NVARCHAR (500) NULL,
    [Field2]          NVARCHAR (500) NULL,
    [Field3]          NVARCHAR (500) NULL,
    [Field4]          NVARCHAR (500) NULL,
    [Field5]          NVARCHAR (500) NULL,
    [Field6]          NVARCHAR (500) NULL,
    [Field7]          NVARCHAR (500) NULL,
    [Field8]          NVARCHAR (500) NULL,
    [Field9]          NVARCHAR (500) NULL,
    [Field10]         NVARCHAR (500) NULL,
    CONSTRAINT [PK_FinancePatner] PRIMARY KEY CLUSTERED ([FinancePatnerId] ASC)
);

