CREATE TABLE [dbo].[ItemHistory] (
    [ItemHistoryId]           BIGINT          IDENTITY (1, 1) NOT NULL,
    [ItemId]                  BIGINT          NOT NULL,
    [ItemName]                NVARCHAR (500)  NOT NULL,
    [ItemNameEnglishLanguage] NVARCHAR (500)  NULL,
    [ItemCode]                NVARCHAR (200)  NOT NULL,
    [ItemShortCode]           NVARCHAR (200)  NULL,
    [PrimaryUnitOfMeasure]    NVARCHAR (20)   NOT NULL,
    [SecondaryUnitOfMeasure]  NVARCHAR (20)   NULL,
    [ProductType]             NVARCHAR (50)   NOT NULL,
    [BussinessUnit]           NVARCHAR (50)   NULL,
    [DangerGoods]             BIT             NULL,
    [Description]             NVARCHAR (500)  NULL,
    [StockInQuantity]         DECIMAL (10, 2) NOT NULL,
    [WeightPerUnit]           DECIMAL (10, 2) NULL,
    [ImageUrl]                NVARCHAR (MAX)  NULL,
    [PackSize]                BIGINT          NULL,
    [BranchPlant]             NVARCHAR (200)  NULL,
    [CreatedBy]               BIGINT          NOT NULL,
    [CreatedDate]             DATETIME        NOT NULL,
    [ModifiedBy]              BIGINT          NULL,
    [ModifiedDate]            DATETIME        NULL,
    [IsActive]                BIT             NOT NULL,
    [SequenceNo]              BIGINT          NULL,
    [PricingUnit]             NVARCHAR (20)   NULL,
    [ShippingUnit]            NVARCHAR (20)   NULL,
    [ComponentUnit]           NVARCHAR (20)   NULL,
    [ItemClass]               NVARCHAR (20)   NULL,
    [ShelfLife]               NVARCHAR (20)   NULL,
    [BBD]                     NVARCHAR (20)   NULL,
    [Barcode]                 NVARCHAR (20)   NULL,
    [ItemOwner]               BIGINT          NULL,
    [Field1]                  NVARCHAR (500)  NULL,
    [Field2]                  NVARCHAR (500)  NULL,
    [Field3]                  NVARCHAR (500)  NULL,
    [Field4]                  NVARCHAR (500)  NULL,
    [Field5]                  NVARCHAR (500)  NULL,
    [Field6]                  NVARCHAR (500)  NULL,
    [Field7]                  NVARCHAR (500)  NULL,
    [Field8]                  NVARCHAR (500)  NULL,
    [Field9]                  NVARCHAR (500)  NULL,
    [Field10]                 NVARCHAR (500)  NULL,
    [ItemType]                NVARCHAR (20)   NULL,
    [AutomatedWareHouseUOM]   BIGINT          NULL,
    [Tax]                     NVARCHAR (50)   NULL,
    [Length]                  DECIMAL (18, 2) NULL,
    [Breadth]                 DECIMAL (18, 2) NULL,
    [Height]                  DECIMAL (18, 2) NULL,
    [Brand]                   NVARCHAR (50)   NULL,
    CONSTRAINT [PK_ItemHistory] PRIMARY KEY CLUSTERED ([ItemHistoryId] ASC)
);

