CREATE TABLE [dbo].[LoginHistory] (
    [LoginHistoryId]          BIGINT         IDENTITY (1, 1) NOT NULL,
    [LoginId]                 BIGINT         NULL,
    [Username]                NVARCHAR (100) NULL,
    [LogoutType]              NVARCHAR (100) NULL,
    [LoggingInTime]           DATETIME       NULL,
    [LoggingOutTime]          DATETIME       NULL,
    [DeviceLoggingInTime]     DATETIME       NULL,
    [DeviceLoggingOutTime]    DATETIME       NULL,
    [AddFrom]                 NVARCHAR (50)  NULL,
    [MACAddress]              NVARCHAR (100) NULL,
    [LoginReason]             NVARCHAR (100) NULL,
    [LogoutReason]            NVARCHAR (100) NULL,
    [LoginStatus]             NVARCHAR (50)  NULL,
    [LoginNetworkStatus]      BIT            NULL,
    [LogoutNetworkStatus]     BIT            NULL,
    [LogOutLatitude]          NVARCHAR (50)  NULL,
    [LogOutLongitude]         NVARCHAR (50)  NULL,
    [LoginLatitude]           NVARCHAR (50)  NULL,
    [LoginLongitude]          NVARCHAR (50)  NULL,
    [LoggingInDeviceUniqueId] NVARCHAR (100) NULL,
    [LogoutDeviceUniqueId]    NVARCHAR (100) NULL,
    [Guid]                    NVARCHAR (100) NULL,
    [IsActive]                BIT            NULL,
    [CreatedDate]             DATETIME       NULL,
    [CreatedBy]               BIGINT         NULL,
    [CreatedFromIPAddress]    NVARCHAR (20)  NULL,
    [UpdatedDate]             DATETIME       NULL,
    [UpdatedBy]               BIGINT         NULL,
    [UpdatedFromIPAddress]    NVARCHAR (20)  NULL,
    CONSTRAINT [PK_LoginHistory] PRIMARY KEY CLUSTERED ([LoginHistoryId] ASC) WITH (FILLFACTOR = 80)
);

