CREATE TABLE [dbo].[LookUp] (
    [LookUpId]       BIGINT         NOT NULL,
    [LookupCategory] BIGINT         NULL,
    [Name]           NVARCHAR (500) NULL,
    [Code]           NVARCHAR (200) NULL,
    [Description]    NVARCHAR (500) NULL,
    [ShortCode]      NVARCHAR (150) NULL,
    [SortOrder]      BIGINT         NULL,
    [ResourceKey]    NVARCHAR (500) NULL,
    [Criteria]       NVARCHAR (500) NULL,
    [ParentId]       BIGINT         NULL,
    [Remarks]        NVARCHAR (MAX) NULL,
    [CreatedBy]      BIGINT         NOT NULL,
    [CreatedDate]    DATETIME       NOT NULL,
    [ModifiedBy]     BIGINT         NULL,
    [ModifiedDate]   DATETIME       NULL,
    [IsActive]       BIT            NOT NULL,
    [SequenceNo]     BIGINT         NULL,
    [Field1]         NVARCHAR (500) NULL,
    [Field2]         NVARCHAR (500) NULL,
    [Field3]         NVARCHAR (500) NULL,
    [Field4]         NVARCHAR (500) NULL,
    [Field5]         NVARCHAR (500) NULL,
    [Field6]         NVARCHAR (500) NULL,
    [Field7]         NVARCHAR (500) NULL,
    [Field8]         NVARCHAR (500) NULL,
    [Field9]         NVARCHAR (500) NULL,
    [Field10]        NVARCHAR (500) NULL,
    [DisplayIcon]    NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_LookUp] PRIMARY KEY CLUSTERED ([LookUpId] ASC) WITH (FILLFACTOR = 80)
);

