CREATE TABLE [dbo].[Notifications] (
    [NotificationsId]  BIGINT         IDENTITY (1, 1) NOT NULL,
    [NotificationType] NVARCHAR (50)  NULL,
    [Subject]          NVARCHAR (500) NULL,
    [Message]          NVARCHAR (MAX) NULL,
    [Sender]           BIGINT         NULL,
    [UserId]           BIGINT         NULL,
    [Actioned]         BIT            NULL,
    [ActionDate]       DATETIME       NULL,
    [IsActionable]     BIT            NULL,
    [Url]              NVARCHAR (250) NULL,
    [QueryString]      NVARCHAR (200) NULL,
    [Type]             NVARCHAR (250) NULL,
    [Remarks]          NVARCHAR (50)  NULL,
    [IsActive]         BIT            NULL,
    [CreatedBy]        BIGINT         NOT NULL,
    [CreatedDate]      DATETIME       CONSTRAINT [DF_Notification_CreatedDate_1] DEFAULT (getdate()) NOT NULL,
    [UpdatedBy]        BIGINT         NULL,
    [UpdatedDate]      DATETIME       NULL,
    [SequenceNo]       BIGINT         NULL,
    [Field1]           NVARCHAR (500) NULL,
    [Field2]           NVARCHAR (500) NULL,
    [Field3]           NVARCHAR (500) NULL,
    [Field4]           NVARCHAR (500) NULL,
    [Field5]           NVARCHAR (500) NULL,
    [Field6]           NVARCHAR (500) NULL,
    [Field7]           NVARCHAR (500) NULL,
    [Field8]           NVARCHAR (500) NULL,
    [Field9]           NVARCHAR (500) NULL,
    [Field10]          NVARCHAR (500) NULL,
    CONSTRAINT [PK_Notification] PRIMARY KEY CLUSTERED ([NotificationsId] ASC) WITH (FILLFACTOR = 80)
);

