CREATE TABLE [dbo].[OrderMovementHistory] (
    [OrderMovementHistoryId] BIGINT         IDENTITY (1, 1) NOT NULL,
    [OrderMovementId]        BIGINT         NOT NULL,
    [OrderId]                BIGINT         NULL,
    [TransportOperatorId]    BIGINT         NULL,
    [DeliveryPersonnelId]    BIGINT         NULL,
    [Location]               BIGINT         NULL,
    [LocationType]           INT            NULL,
    [Action]                 INT            NULL,
    [State]                  BIGINT         NULL,
    [StartTime]              DATETIME       NULL,
    [PraposedTimeOfAction]   DATETIME       NULL,
    [PraposedShift]          NVARCHAR (50)  NULL,
    [ExpectedTimeOfAction]   DATETIME       NULL,
    [ExpectedShift]          NVARCHAR (50)  NULL,
    [ActualTimeOfAction]     DATETIME       NULL,
    [Latitude]               NVARCHAR (250) NULL,
    [Longitude]              NVARCHAR (250) NULL,
    [GroupName]              NVARCHAR (250) NULL,
    [GroupRouteCode]         NVARCHAR (250) NULL,
    [IsActive]               BIT            NULL,
    [CreatedBy]              BIGINT         NULL,
    [CreatedDate]            DATETIME       CONSTRAINT [DF_OrderMovementHistory_CreatedDate] DEFAULT (getdate()) NULL,
    [UpdateBy]               BIGINT         NULL,
    [UpdatedDate]            DATETIME       NULL,
    [OrderMovmentGuid]       NVARCHAR (250) NULL,
    [IsUnloadGroup]          BIT            NULL,
    [IsMarkedDraft]          BIT            CONSTRAINT [DF_OrderMovementHistory_IsMarkedDraft] DEFAULT ((0)) NULL,
    [PlanNumber]             NVARCHAR (250) NULL,
    CONSTRAINT [PK_OrderMovementHistory] PRIMARY KEY CLUSTERED ([OrderMovementHistoryId] ASC)
);

