CREATE TABLE [dbo].[ProcessConfiguration] (
    [ProcessConfigurationId] BIGINT         IDENTITY (1, 1) NOT NULL,
    [CompanyType]            NVARCHAR (200) NULL,
    [OrderType]              NVARCHAR (200) NULL,
    [CompanyID]              BIGINT         NOT NULL,
    [ModeOfDelivery]         NVARCHAR (200) NULL,
    [ProcessCategory]        NVARCHAR (200) NULL,
    [LastStageId]            BIGINT         NULL,
    [ProcessName]            NVARCHAR (500) NULL,
    [NextStageId]            BIGINT         NULL,
    [RuleId]                 BIGINT         NULL,
    [NotificationId]         BIGINT         NULL,
    [Remarks]                NVARCHAR (MAX) NULL,
    [CreatedBy]              BIGINT         NOT NULL,
    [CreatedDate]            DATETIME       NOT NULL,
    [ModifiedBy]             BIGINT         NULL,
    [ModifiedDate]           DATETIME       NULL,
    [IsActive]               BIT            NOT NULL,
    [SequenceNo]             BIGINT         NULL,
    [Field1]                 NVARCHAR (500) NULL,
    [Field2]                 NVARCHAR (500) NULL,
    [Field3]                 NVARCHAR (500) NULL,
    [Field4]                 NVARCHAR (500) NULL,
    [Field5]                 NVARCHAR (500) NULL,
    [Field6]                 NVARCHAR (500) NULL,
    [Field7]                 NVARCHAR (500) NULL,
    [Field8]                 NVARCHAR (500) NULL,
    [Field9]                 NVARCHAR (500) NULL,
    [Field10]                NVARCHAR (500) NULL,
    CONSTRAINT [PK_ProcessConfiguration] PRIMARY KEY CLUSTERED ([ProcessConfigurationId] ASC) WITH (FILLFACTOR = 80)
);

