CREATE TABLE [dbo].[TransportVehicle] (
    [TransportVehicleId]               BIGINT         IDENTITY (1, 1) NOT NULL,
    [VehicleName]                      NVARCHAR (500) NOT NULL,
    [VehicleRegistrationNumber]        NVARCHAR (200) NULL,
    [TransporterId]                    BIGINT         NULL,
    [VehicleTypeId]                    BIGINT         NULL,
    [NumberOfCompartments]             BIGINT         NULL,
    [TruckSizeId]                      BIGINT         NULL,
    [SequenceNumber]                   BIGINT         NULL,
    [IsVehicleInsured]                 BIT            NULL,
    [InsuranceValidityDate]            DATETIME       NULL,
    [IsFitnessCertificateAvailed]      BIT            NULL,
    [FitnessCertificateDate]           DATETIME       NULL,
    [VehicleOwnerName]                 NVARCHAR (40)  NULL,
    [VehicleOwnerAddress1]             NVARCHAR (30)  NULL,
    [VehicleOwnerAddress2]             NVARCHAR (30)  NULL,
    [FormatType]                       NVARCHAR (50)  NULL,
    [RegisteredVehicleCertificateBlob] NVARCHAR (MAX) NULL,
    [Field1]                           NVARCHAR (500) NULL,
    [Field2]                           NVARCHAR (500) NULL,
    [Field3]                           NVARCHAR (500) NULL,
    [Field4]                           NVARCHAR (500) NULL,
    [Field5]                           NVARCHAR (500) NULL,
    [Field6]                           NVARCHAR (500) NULL,
    [Field7]                           NVARCHAR (500) NULL,
    [Field8]                           NVARCHAR (500) NULL,
    [Field9]                           NVARCHAR (500) NULL,
    [Field10]                          NVARCHAR (500) NULL,
    [IsActive]                         BIT            NOT NULL,
    [CreatedBy]                        BIGINT         NOT NULL,
    [CreatedDate]                      DATETIME       NOT NULL,
    [UpdatedBy]                        BIGINT         NULL,
    [UpdatedDate]                      DATETIME       NULL,
    CONSTRAINT [PK_TransporterVehicle] PRIMARY KEY CLUSTERED ([TransportVehicleId] ASC) WITH (FILLFACTOR = 80)
);

