CREATE TABLE [dbo].[Transporter] (
    [TransporterId]       BIGINT         IDENTITY (1, 1) NOT NULL,
    [TransporterName]     NVARCHAR (500) NOT NULL,
    [TransporterCode]     NVARCHAR (200) NULL,
    [TypeOfCarrier]       NVARCHAR (50)  NULL,
    [AddressLine1]        NVARCHAR (MAX) NULL,
    [AddressLine2]        NVARCHAR (MAX) NULL,
    [AddressLine3]        NVARCHAR (MAX) NULL,
    [City]                NVARCHAR (100) NULL,
    [State]               NVARCHAR (100) NULL,
    [CountryId]           BIGINT         NOT NULL,
    [Postcode]            NVARCHAR (20)  NULL,
    [Region]              NVARCHAR (20)  NULL,
    [RouteCode]           NVARCHAR (20)  NULL,
    [BranchPlant]         NVARCHAR (200) NULL,
    [Email]               NVARCHAR (MAX) NULL,
    [SiteURL]             NVARCHAR (200) NULL,
    [ContactPersonNumber] NVARCHAR (20)  NULL,
    [ContactPersonName]   NVARCHAR (500) NULL,
    [logo]                NVARCHAR (MAX) NULL,
    [CreatedBy]           BIGINT         NOT NULL,
    [CreatedDate]         DATETIME       NOT NULL,
    [ModifiedBy]          BIGINT         NULL,
    [ModifiedDate]        DATETIME       NULL,
    [IsActive]            BIT            NOT NULL,
    [SequenceNo]          BIGINT         NULL,
    [Field1]              NVARCHAR (500) NULL,
    [Field2]              NVARCHAR (500) NULL,
    [Field3]              NVARCHAR (500) NULL,
    [Field4]              NVARCHAR (500) NULL,
    [Field5]              NVARCHAR (500) NULL,
    [Field6]              NVARCHAR (500) NULL,
    [Field7]              NVARCHAR (500) NULL,
    [Field8]              NVARCHAR (500) NULL,
    [Field9]              NVARCHAR (500) NULL,
    [Field10]             NVARCHAR (500) NULL,
    CONSTRAINT [PK_Transporter] PRIMARY KEY CLUSTERED ([TransporterId] ASC) WITH (FILLFACTOR = 80)
);

